---
- set_fact:
    prometheus_docker_network_ipv4: "{{ prometheus_docker_network_subnet | ipv4('net') }}"

- name: Create MySQL user.
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: mysql_user
    module_args:
      login_host: "{{ database_address }}"
      login_user: "root"
      login_password: "{{ database_password }}"
      name: "{{ prometheus_mysql_exporter_user }}"
      host: "%"
      password: "{{ prometheus_mysql_exporter_password }}"
      priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
  delegate_to: "{{ groups['control'][0] }}"
  run_once: True

- name: Configure MySQL exporter.
  template:
    src: mysql_exporter.my.cnf.j2
    dest: "{{ service.config_dir }}/my.cnf"
  notify:
    - restart mysql exporter
