---
- name: Pull Nginx image.
  docker_image:
    name: "{{ nginx_docker_image }}"

- name: Create basic Nginx config.
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: Create Nginx config directory.
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: Generate Diffie-Hellman parameters.
  openssl_dhparam:
    path: /etc/nginx/dhparams.pem
    size: 2048

- name: Add Nginx systemd service (nginx.service).
  systemdunit:
    name: 'nginx.service'
    state: present
    content: |
      [Unit]
      Description=Nginx server
      After=docker.service
      [Service]
      Restart=always
      ExecStart=/bin/docker run --name=nginx \
                                -v /etc/nginx:/etc/nginx \
                                -v /etc/pki/tls:/certs \
                                -p 443:443 \
                                {{ nginx_docker_image }}
      ExecStop=/bin/docker stop -t 2 nginx
      ExecStopPost=/bin/docker rm -f nginx
      [Install]
      WantedBy=multi-user.target
