---
- name: Create Docker network.
  docker_network:
    name: "{{ nginx_docker_network_name }}"

- name: Pull Nginx image.
  docker_image:
    name: "{{ nginx_docker_image }}"
  tags:
    - pull

- name: Create Nginx config directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/nginx
    - /etc/nginx/conf.d

- name: Generate Diffie-Hellman parameters.
  openssl_dhparam:
    path: /etc/nginx/dhparams.pem
    size: 2048

- name: Configure Nginx.
  block:
    - name: Create basic Nginx config.
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify:
        - reload nginx
    - name: Configure Nginx systemd service (nginx.service).
      template:
        src: nginx.service.j2
        dest: /etc/systemd/system/nginx.service
      notify:
        - restart nginx
  tags:
    - configuration
    - nginx

- name: Enable Nginx on boot.
  systemd:
    name: nginx
    # TODO: this is a thorny part of ansible and we shouldn't have to do this ourselves.
    daemon_reload: yes
    state: started
    enabled: yes
