---
chameleon_resource_discovery_docker_image: "{{ chameleon_site_tools_image_full }}"
chameleon_resource_discovery_config_dir: /etc/hammers

chameleon_resource_discovery_parallel: 5
chameleon_resource_discovery_limit: 5
chameleon_resource_discovery_provide_manageable: true
chameleon_resource_discovery_reinspect_failed: true
chameleon_resource_discovery_expire_days: 7
