---
mysql_port: 3306

mysql_prometheus_exporter_enable: False
mysql_prometheus_exporter_port: 9104
mysql_prometheus_exporter_docker_image: prom/mysqld-exporter:v0.11.0
mysql_prometheus_exporter_service_name: prometheus-mysqld-exporter
mysql_prometheus_exporter_config_path: /etc/prometheus/mysqld-exporter
mysql_prometheus_exporter_mysql_user: mysqld-exporter
# Implementor must provide this securely somehow!
# mysql_prometheus_exporter_mysql_password: changeme
