---
- name: Pull Grafana image.
  docker_image:
    name: "{{ grafana_docker_image }}"

- name: Configure Grafana systemd service (grafana.service).
  template:
    src: grafana.service.j2
    dest: /etc/systemd/system/grafana.service
  tags: systemd
  notify:
    - restart grafana

- name: Enable Grafana service on boot.
  systemd:
    service: grafana.service
    # TODO: this is a thorny part of ansible and we shouldn't have to do this ourselves.
    daemon_reload: yes
    state: started
    enabled: yes
  tags: systemd

- name: Create Nginx configuration for proxy to Grafana.
  include_role:
    name: nginx
    tasks_from: host
  vars:
    nginx_server_name: "{{ grafana_hostname }}"
    nginx_server_conf: |
      location / {
        proxy_pass http://grafana:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
