---
- name: Pull Keycloak images.
  docker_image:
    source: pull
    name: "{{ item.value.image }}"
    force_source: yes
  loop: "{{ keycloak_services|dict2items }}"
  loop_control:
    label: "{{ item.value.image }}"
  tags:
    - pull

- name: Create Keycloak network.
  docker_network:
    name: "{{ keycloak_docker_network }}"
    ipam_config:
      - subnet: "{{ keycloak_docker_network_subnet }}"

- name: Configure Keycloak services.
  chi_docker_service:
    name: "{{ item.key }}"
    image: "{{ item.value.image }}"
    network: "{{ item.value.network }}"
    environment: "{{ item.value.environment }}"
    mounts: "{{ item.value.mounts }}"
    ports: "{{ item.value.ports|default([]) }}"
  loop: "{{ keycloak_services|dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Configure haproxy for Keycloak
  import_role:
    name: haproxy-config
  vars:
    project_services: "{{ keycloak_services }}"
  when: enable_haproxy | bool
