---
- name: Pull Keycloak images.
  docker_image:
    source: pull
    name: "{{ item.value.image }}"
    force_source: yes
  loop: "{{ keycloak_services|dict2items }}"
  loop_control:
    label: "{{ item.value.image }}"
  tags:
    - pull

- name: Create Keycloak network.
  docker_network:
    name: "{{ keycloak_docker_network }}"
    ipam_config:
      - subnet: "{{ keycloak_docker_network_subnet }}"

- name: Configure Keycloak services.
  include_role:
    name: diurnalist.docker_service
  vars:
    service_name: "{{ item.key }}"
    service_bind_address: "{{ api_interface_address }}"
    docker_image: "{{ item.value.image }}"
    docker_network: "{{ item.value.network }}"
    docker_environment: "{{ item.value.environment }}"
    docker_mounts: "{{ item.value.mounts }}"
    docker_ports: "{{ item.value.ports|default([]) }}"
  loop: "{{ keycloak_services|dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Configure haproxy for Keycloak
  import_role:
    name: haproxy-config
  vars:
    project_services: "{{ keycloak_services }}"
  when: enable_haproxy | bool

- name: Create periodic realm export script.
  copy:
    src: keycloak_backup_realm.sh
    dest: /usr/local/sbin/keycloak_backup_realm.sh
    mode: "0700"

- name: Configure periodic realm export.
  include_role:
    name: diurnalist.periodic_task
  vars:
    task_name: keycloak_backup_realm
    task_calendar: daily
    task_command: "/usr/local/sbin/keycloak_backup_realm.sh {{ keycloak_realm_name }}"
