---

extra_auth:
  project_name: "{{ keystone_admin_project }}"
  project_domain_name: "default"

project_auth: "{{ openstack_auth | combine(extra_auth) }}"

kvm_flavors:
  - name: m1.tiny
    vcpus: 1
    ram: 1
    disk: 1
    is_public: no
  - name: m1.small
    vcpus: 1
    ram: 2
    disk: 10
    is_public: no
  - name: m1.medium
    vcpus: 2
    ram: 4
    disk: 20
    is_public: no
  - name: m1.large
    vcpus: 4
    ram: 8
    disk: 20
    is_public: no
  - name: m1.xlarge
    vcpus: 8
    ram: 16
    disk: 20
    is_public: no

kvm_glance_images:
  - name: cirros
    container_format: bare
    disk_format: qcow2
    url: "http://download.cirros-cloud.net/0.5.1/cirros-0.5.1-x86_64-disk.img"
  - name: Ubuntu20.04
    container_format: bare
    disk_format: qcow2
    url: "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
  - name: CentOS-Stream8
    container_format: bare
    disk_format: qcow2
    url: "https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20220125.1.x86_64.qcow2"
