# This task is intended to be imported from another task when you need
# to set up a virtual host a running Apache server.
#
# Example:
#
#   - name: Create Apache configuration for proxy to Grafana.
#     include_role:
#       name: apache
#       tasks_from: host
#       vars:
#         apache_server_name: "{{ grafana_server_name }}"
#         apache_server_conf: |
#           ProxyPass / http://{{ grafana_host }}:{{ grafana_port }}/
#           ProxyPassReverse / http://{{ grafana_host }}:{{ grafana_port }}/
#
---
- name: "Create Apache configuration for {{ apache_server_name }}"
  template:
    src: vhost.conf.j2
    dest: "/etc/httpd/conf.d/100-{{ apache_server_name }}.conf"
    mode: 0644
  tags:
    - configuration
    - apache
  notify:
    - reload apache
