---
- name: Install dependencies for Apache.
  package:
    name: "{{ item }}"
  loop:
    - httpd
    # For external authentication via Keystone
    - mod_authnz_external
    # For HTTP Authentication via LDAP
    - mod_ldap
    # For SSL termination
    - mod_ssl
    # For Python web server support
    - mod_wsgi
    # For issuing/renewing SSL certificates through LetsEncrypt
    - python2-certbot-apache

- name: Install external Keystone authentication scripts.
  template:
    src: "{{ item }}.j2"
    dest: "{{ apache_config_path }}/{{ item }}"
    mode: a+x
  loop:
    - keystone_user.sh

- name: Create cron job to periodically renew LetsEncrypt certificates.
  cron:
    name: Check for SSL certificate renewals
    minute: 0
    hour: 4,21
    # Adding some jitter is recommended to avoid load on the LE servers
    job:
      python -c 'import random; import time; time.sleep(random.random() * 3600)'
        && certbot renew
        | /usr/bin/logger -t certbot

- debug:
    msg: |
      TODO: include basic global Apache configuration.
      This should include setting up the external authentication module:
        AddExternalAuth keystone /path/to/keystone_auth.sh
        SetExternalAuthMethod keystone pipe

- name: Enable Apache on boot.
  systemd:
    name: "{{ apache_service_name }}"
    # TODO: this is a thorny part of ansible and we shouldn't have to do this ourselves.
    daemon_reload: yes
    state: started
    enabled: yes

- name: Create cron job to periodically renew certificates.
  cron:
    name: "Renew SSL certificate for all domains."
    minute: 0
    hour: 5,2
    job: "certbot renew"
  when: apache_ssl_letsencrypt_enabled
