#!/usr/bin/env bash
set -e -u -o pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
current_inventory="$DIR/.ansible-inventory"
vault_password="$DIR/vault_password"

if [[ -f "$current_inventory" ]]; then
  echo "It looks like an inventory has already been initialized."
  echo "Current inventory: '$(cat "$current_inventory")'"
  exit 0
fi

read -p "Enter the name of the inventory: " name

inventory_dir="$DIR/inventories/$name"

echo "Creating inventory directory structure: "
echo "  - ./inventories/$name"
mkdir -p "$inventory_dir"
echo "  - ./inventories/$name/group_vars/ansible"
mkdir -p "$inventory_dir/group_vars"
cat >"$inventory_dir/group_vars/ansible" <<ANSIBLE_GROUP_VARS
---
ansible_connection: local
pip_virtualenv: $DIR/venv
ANSIBLE_GROUP_VARS

echo "Creating initial hosts file: "
echo "  - ./inventories/$name/hosts"
cat >"$inventory_dir/hosts" <<INVENTORY_HOSTS
# Ansible inventory for '$name'
# Not sure what this is? https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

# The Ansible deployment host
[ansible]
$(hostname)

# The primary OpenStack controller host
# [controller]

# The Ceph cluster hosts
# [ceph]

# The Ceph cluster monitoring host (usually the master)
# [ceph_exporter]

# The MySQL host(s)
# [mysql]

# The MySQL hosts to install metrics exporters on
# [mysql_exporter]

# The Prometheus server host
# [prometheus]

# By default node metric exporters will be installed on all
# hosts in all groups. Comment out host groups you don't want
# to install the node exporters on.
[node_exporters:children]
ansible
controller
ceph
mysql
prometheus
INVENTORY_HOSTS

echo "Creating initial vault password in ./vault_password"
openssl rand -base64 2048 > "$vault_password"
chmod 400 "$vault_password"

echo -n "$name" > "$current_inventory"
echo "Your new inventory environment is now set up."
