#!/usr/bin/env bash
# This is just a really simple wrapper around ansible-playbook, which is the
# most commonly used utility when provisioning. It uses the inventory set up
# on the host (with ./ansible-inventory) and pre-sets a few variables.
set -e -u -o pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
inventory_name="$(cat "$DIR/.ansible-inventory")"

exec venv/bin/ansible-playbook \
  --vault-id="${inventory_name}@vault_password" \
  --inventory="$DIR/inventories/${inventory_name}" \
  "$@"
