#!/usr/bin/env bash
# This is just a really simple wrapper around ansible-playbook, which is the
# most commonly used utility when provisioning. It uses the inventory set up
# on the host (with ./ansible-inventory) and pre-sets a few variables.
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
inventory_name="$(cat "$DIR/.ansible-inventory")"

source venv/bin/activate
ansible-playbook \
  --vault-id="${inventory_name}@vault_password" \
  --inventory="$DIR/environments/${inventory_name}/inventory" \
  --extra-vars=node_custom_config="$DIR/kolla/node_custom_config" \
  "$@"
