#!/usr/bin/env bash
# This is just a really simple wrapper around ansible-vault, which sets the
# property vault ID.
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
inventory_name="$(cat "$DIR/.ansible-inventory")"

source venv/bin/activate
ansible-vault --vault-id="${inventory_name}@vault_password" "$@"
