#!/usr/bin/env bash
# This is just a really simple wrapper around ansible-vault, which sets the
# property vault ID.
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
ansible_dir="${ANSIBLE_DIR:-$DIR}"
inventory_name="$(cat "$ansible_dir/.ansible-inventory")"

source "$DIR/venv/bin/activate"
ansible-vault --vault-id="${inventory_name}@${ansible_dir}/vault_password" "$@"
