#!/usr/bin/env bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

declare -a cmd=("$DIR/cc-ansible" "$@")

echo "WARNING: This command is deprecated! Please use the updated invocation:"
echo "  $(basename ${cmd[0]}) ${cmd[@]:1}"
echo
echo "As a punishment you now have to wait a couple seconds."
echo
sleep 3

"${cmd[@]}"
