site_name: CHI-in-a-Box
site_dir: public
site_url: https://chameleoncloud.github.io/chi-in-a-box/
repo_url: https://github.com/ChameleonCloud/chi-in-a-box/

plugins:
  - search

theme:
  name: material
  palette:
    scheme: chameleon
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.sections
    - navigation.expand


extra_css:
  - stylesheets/extra.css

# nav:
  # - README.md
  # - 'Getting Started':
  #   - "Assumed Knowledge": usage_guides/upstream-docs.md
  #   - Concepts:
  #     - "The Deploy Process": usage_guides/how-deployment-works.md
  #     - "Hosts and Services": usage_guides/hosts-and-services.md
  #     - "Network Overview": usage_guides/openstack-architecture.md
  #     - "CC-Ansible": usage_guides/command-line-interface.md
  #     - "The Site Config": usage_guides/site-config.md
  #   - "Quick Start for Evaluation": usage_guides/quickstart.md
  #   - "Quick Start for Development": usage_guides/dev-in-a-box.md
  #   - "Production Considerations":
  #     - usage_guides/production/security.md
