---
- name: Configure mariadb backup script file
  become: True
  template:
    src: mariadb.j2
    mode: 0700
    dest: "{{ mariadb_backup_cron_script }}"

- name: Add mariadb backup job
  include_role:
    name: chameleon.periodic_task
    apply:
      become: yes
  vars:
    task_name: "mariadb_backup"
    task_command: "{{ mariadb_backup_cron_script }}"
    task_calendar: "00:00"
