---
# this depends on the location of chi-in-a-box and site-config directories, and will break if they're moved.
# to check on the success of the backup, login to the mariadb host and check if the backups are in the
# mariadb_backup docker volume.
# if it breaks because of moving directories, simply re-run post-deploy.
- name: Add mariadb backup job
  include_role:
    name: chameleon.periodic_task
    apply:
      become: yes
  vars:
    task_name: "mariadb_backup_{{ mariadb_backup_timer_suffix }}"
    task_command: "{{ deployment_dir }}/cc-ansible --site {{ deployment_site_config_dir }} mariadb_backup"
    task_calendar: "23:00"
