---
- name: Include cron notification script
  include_role:
    name: chameleon_common
    tasks_from: cron
    defaults_from: cron

- name: Configure mariadb backup script file
  template:
    src: mariadb.j2
    mode: 0700
    dest: "{{ mariadb_backup_cron_script }}"
  when: inventory_hostname_short == "m01-07"

- name: Configure mariadb backup script file without rsync for dev
  template:
    src: mariadbdev.j2
    mode: 0700
    dest: "{{ mariadb_backup_cron_script }}"
  when: inventory_hostname_short == "dev"

- name: Create directory to mount to aws-cli docker container for copying config and backup files to container
  file:
    path: /etc/awsconf
    state: directory
  when: inventory_hostname_short == "admin01" or
        inventory_hostname_short == "admin02"

- name: Configure mariadb backup script file
  template:
    src: mariadb_uc.j2
    mode: 0700
    dest: "{{ mariadb_backup_cron_script }}"
  when: inventory_hostname_short == "admin01" or
        inventory_hostname_short == "admin02"

- name: Configure s3 config file
  template:
    src: mariadb_uc_x-site_config.j2
    mode: 0700
    dest: "{{ mariadb_backup_s3_conf_dir }}/config"
  when: inventory_hostname_short == "admin01" or
        inventory_hostname_short == "admin02"

- name: Configure mariadb backup script file
  template:
    src: mariadb_uc_x-site_credentials.j2
    mode: 0700
    dest: "{{ mariadb_backup_s3_conf_dir }}/credentials"
  when: inventory_hostname_short == "admin01" or
        inventory_hostname_short == "admin02"

- name: Add mariadb backup cron jobs.
  cron:
    name: "{{ mariadb_backup_cron_name }}"
    minute: "{{ mariadb_backup_cron_minute }}"
    hour: "{{ mariadb_backup_cron_hour }}"
    day: "{{ mariadb_backup_cron_day }}"
    month: "{{ mariadb_backup_cron_month }}"
    weekday: "{{ mariadb_backup_cron_weekday }}"
    job: "{{ mariadb_backup_cron_script }} && {{ cron_notification }} mariadb-backup"
