groups:
- name: baremetal
  rules:
  - alert: NovaIronicInstanceLaunchFailure
    expr: sum(increase(launch_failure[1h])) by (hostname) > 3
    labels:
      severity: warning
      can_resolve: no
    annotations:
      summary: "Instance launches are failing"
      description: "A significant number of instance launches on {{ $labels.hostname }} have failed in the past hour."

  - alert: IronicNodeInErrorState
    expr: sum(openstack_node_totals{provision_state="error",maintenance="False"}) by (hostname, name)
    labels:
      severity: critical
    annotations:
      summary: "Ironic node in error provision state"
      description: "Ironic node {{ $labels.name }} on {{ $labels.hostname }} is in an error provision state."
      runbook: https://github.com/ChameleonCloud/chi-in-a-box/wiki/%5BRunbook%5D-IronicNodeInErrorState

  - alert: IronicNodeConsoleDisabled
    expr: sum(openstack_node_totals{console_enabled="False",provision_state="active",maintenance="False"}) by (hostname, name)
    labels:
      severity: warning
    annotations:
      summary: "Ironic node's serial console is disabled"
      description: "Node {{ $labels.name }} on {{ $labels.hostname }} does not have a serial console enabled."
      runbook: https://github.com/ChameleonCloud/chi-in-a-box/wiki/%5BRunbook%5D-IronicNodeConsoleDisabled
