---

audit_blazar_computehosts: false
audit_blazar_computehost_extra_capabilities: "{{ audit_blazar_computehosts }}"
audit_blazar_resource_properties: "{{ audit_blazar_computehosts }}"
audit_blazar_leases: false
audit_blazar_reservations: "{{ audit_blazar_leases }}"
audit_blazar_computehost_allocations: "{{ audit_blazar_leases }}"
audit_blazar_computehost_reservations: "{{ audit_blazar_leases }}"
audit_blazar_instance_reservations: "{{ audit_blazar_leases }}"

audit_nova_compute_nodes: false
audit_nova_services: "{{ audit_nova_compute_nodes }}"
audit_nova_instances: false
audit_nova_instance_actions: "{{ audit_nova_instances }}"
audit_nova_instance_actions_events: "{{ audit_nova_instances }}"

audit_ironic_nodes: false

audit_tables:
  - name: blazar_computehosts
    source_db: blazar
    source_table: computehosts
    grant_user: blazar
    id_type: "VARCHAR(36)"
    enabled: "{{ audit_blazar_computehosts }}"
    columns:
      - id
      - hypervisor_hostname
      - vcpus
      - memory_mb
      - local_gb
      - status
      - reservable
      - disabled
      - created_at
      - deleted_at
    watch_columns:
      - status
      - reservable
      - disabled
  - name: blazar_computehost_extra_capabilities
    source_db: blazar
    source_table: computehost_extra_capabilities
    grant_user: blazar
    id_type: "VARCHAR(36)"
    enabled: "{{ audit_blazar_computehost_extra_capabilities }}"
    columns:
      - created_at
      - updated_at
      - deleted_at
      - id
      - computehost_id
      - capability_value
      - property_id
    watch_columns:
      - capability_value
  - name: blazar_resource_properties
    source_db: blazar
    source_table: resource_properties
    grant_user: blazar
    id_type: "VARCHAR(36)"
    enabled: "{{ audit_blazar_resource_properties }}"
    columns:
      - created_at
      - updated_at
      - deleted_at
      - id
      - resource_type
      - property_name
      - private
      - is_unique
    watch_columns:
      - property_name
      - private
      - is_unique
  - name: blazar_leases
    source_db: blazar
    source_table: leases
    grant_user: blazar
    id_type: "VARCHAR(36)"
    enabled: "{{ audit_blazar_leases }}"
    columns:
      - created_at
      - updated_at
      - deleted_at
      - deleted
      - id
      - name
      - user_id
      - project_id
      - start_date
      - end_date
      - trust_id
      - status
      - degraded
    watch_columns:
      - name
      - start_date
      - end_date
      - status
      - degraded
  - name: blazar_reservations
    source_db: blazar
    source_table: reservations
    grant_user: blazar
    id_type: "VARCHAR(36)"
    enabled: "{{ audit_blazar_reservations }}"
    columns:
      - created_at
      - updated_at
      - deleted_at
      - deleted
      - id
      - lease_id
      - resource_id
      - resource_type
      - status
      - missing_resources
      - resources_changed
    watch_columns:
      - resource_id
      - resource_type
      - status
      - missing_resources
      - resources_changed
  - name: blazar_computehost_allocations
    source_db: blazar
    source_table: computehost_allocations
    grant_user: blazar
    id_type: "VARCHAR(36)"
    enabled: "{{ audit_blazar_computehost_allocations }}"
    columns:
      - created_at
      - updated_at
      - deleted_at
      - deleted
      - id
      - compute_host_id
      - reservation_id
    watch_columns:
      - compute_host_id
      - reservation_id
  - name: blazar_computehost_reservations
    source_db: blazar
    source_table: computehost_reservations
    grant_user: blazar
    id_type: "VARCHAR(36)"
    enabled: "{{ audit_blazar_computehost_reservations }}"
    columns:
      - created_at
      - updated_at
      - deleted_at
      - deleted
      - id
      - reservation_id
      - aggregate_id
      - resource_properties
      - count_range
      - hypervisor_properties
      - before_end
      - on_start
    watch_columns:
      - aggregate_id
      - resource_properties
      - hypervisor_properties
      - count_range
      - on_start
      - before_end
  - name: blazar_instance_reservations
    source_db: blazar
    source_table: instance_reservations
    grant_user: blazar
    id_type: "VARCHAR(36)"
    enabled: "{{ audit_blazar_instance_reservations }}"
    columns:
      - created_at
      - updated_at
      - deleted_at
      - deleted
      - id
      - reservation_id
      - vcpus
      - memory_mb
      - disk_gb
      - amount
      - affinity
      - flavor_id
      - aggregate_id
      - server_group_id
      - resource_properties
    watch_columns:
      - vcpus
      - memory_mb
      - disk_gb
      - amount
      - affinity
      - flavor_id
      - aggregate_id
      - server_group_id
      - resource_properties
  - name: nova_compute_nodes
    source_db: nova
    source_table: compute_nodes
    grant_user: nova
    id_type: "INT(11)"
    enabled: "{{ audit_nova_compute_nodes }}"
    columns:
      - created_at
      - updated_at
      - deleted_at
      - id
      - service_id
      - vcpus
      - memory_mb
      - local_gb
      - vcpus_used
      - memory_mb_used
      - local_gb_used
      - hypervisor_type
      - hypervisor_version
      - current_workload
      - running_vms
      - hypervisor_hostname
      - host_ip
      - supported_instances
      - host
      - ram_allocation_ratio
      - cpu_allocation_ratio
      - uuid
      - disk_allocation_ratio
      - mapped
    watch_columns:
      - vcpus
      - cpu_allocation_ratio
      - memory_mb
      - ram_allocation_ratio
      - local_gb
      - disk_allocation_ratio
      - hypervisor_hostname
      - host
      - hypervisor_version
      - supported_instances
      - mapped
  - name: nova_services
    source_db: nova
    source_table: services
    grant_user: nova
    id_type: "INT(11)"
    enabled: "{{ audit_nova_services }}"
    columns:
      - created_at
      - updated_at
      - deleted_at
      - id
      - host
      - binary
      - topic
      - report_count
      - disabled
      - disabled_reason
      - last_seen_up
      - forced_down
      - version
      - uuid
    watch_columns:
      - host
      - binary
      - topic
      - disabled
      - disabled_reason
      - forced_down
      - version
  - name: nova_instances
    source_db: nova
    source_table: instances
    grant_user: nova
    id_type: "INT(11)"
    enabled: "{{ audit_nova_instances }}"
    columns:
      - created_at
      - updated_at
      - deleted_at
      - id
      - internal_id
      - user_id
      - project_id
      - image_ref
      - kernel_id
      - ramdisk_id
      - launch_index
      - key_name
      # - key_data
      - power_state
      - vm_state
      - memory_mb
      - vcpus
      - hostname
      - host
      # - user_data
      - reservation_id
      - launched_at
      - terminated_at
      - display_name
      - display_description
      - availability_zone
      - locked
      - os_type
      - launched_on
      - instance_type_id
      - vm_mode
      - uuid
      - architecture
      - root_device_name
      - access_ip_v4
      - access_ip_v6
      - config_drive
      - task_state
      - default_ephemeral_device
      - default_swap_device
      - progress
      - auto_disk_config
      - shutdown_terminate
      - disable_terminate
      - root_gb
      - ephemeral_gb
      - cell_name
      - node
      - deleted
      - locked_by
      - cleaned
      - ephemeral_key_uuid
      - hidden
    watch_columns:
      - power_state
      - vm_state
      - task_state
      - host
      - node
      - launched_at
      - terminated_at
      - locked
      - locked_by
      - availability_zone
      - instance_type_id
      - deleted
      - hidden
  - name: nova_instance_actions
    source_db: nova
    source_table: instance_actions
    grant_user: nova
    id_type: "INT(11)"
    enabled: "{{ audit_nova_instance_actions }}"
    columns:
      - created_at
      - updated_at
      - deleted_at
      - id
      - action
      - instance_uuid
      - request_id
      - user_id
      - project_id
      - start_time
      - finish_time
      - message
      - deleted
    watch_columns:
      - finish_time
      - message
  - name: nova_instance_actions_events
    source_db: nova
    source_table: instance_actions_events
    grant_user: nova
    id_type: "INT(11)"
    enabled: "{{ audit_nova_instance_actions_events }}"
    columns:
      - created_at
      - updated_at
      - deleted_at
      - id
      - event
      - action_id
      - start_time
      - finish_time
      - result
      - traceback
      - deleted
      - host
      - details
    watch_columns:
      - finish_time
      - result
      - host
  - name: ironic_nodes
    source_db: ironic
    source_table: nodes
    grant_user: ironic
    id_type: "INT(11)"
    enabled: "{{ audit_ironic_nodes }}"
    columns:
      - created_at
      - updated_at
      - id
      - uuid
      - instance_uuid
      - power_state
      - target_power_state
      - provision_state
      - target_provision_state
      - last_error
      - driver
      - reservation
      - maintenance
      - provision_updated_at
      - instance_info
      - maintenance_reason
      - name
      - resource_class
      - owner
      - lessee
      - retired
      - retired_reason
      - fault
    watch_columns:
      # - power_state # will change multiple times per instance
      # - provision_state # will change multiple times per instance
      # - instance_uuid # we'll get this from instance table
      - maintenance
      - maintenance_reason
      - retired
      - owner   # shouldn't change, but maybe in future
      - lessee  # shouldn't change, but maybe in future
      - fault
      - resource_class
