---
- name: Create Ceph configuration directory.
  file:
    path: /etc/ceph
    state: directory

- name: Copy global Ceph configuration.
  block:
    - slurp:
        src: /etc/ceph/ceph.conf
      delegate_to: "{{ groups.ceph[0] }}"
      register: ceph_conf
    - copy:
        content: "{{ ceph_conf['content'] | b64decode }}"
        dest: /etc/ceph/ceph.conf

- name: Copy Ceph client keyring.
  block:
    - command: "ceph auth get {{ jupyterhub_ceph_client }}"
      register: ceph_client_keyring
      delegate_to: "{{ groups.ceph[0] }}"
    - copy:
        content: "{{ ceph_client_keyring.stdout }}"
        dest: "/etc/ceph/ceph.{{ jupyterhub_ceph_client }}.keyring"

- name: Install Docker RBD volume plugin.
  block:
    - name: Checking if plugin already installed.
      command: >
        docker plugin ls --format '{{ '{{' }} .Name {{ '}}' }}' \
          --filter enabled=true --filter capability=volumedriver
      register: docker_plugin_list
    - name: Installing plugin.
      command: >
        docker plugin install "{{ jupyterhub_ceph_docker_volume_driver }}" \
          --grant-all-permissions \
          --alias="{{ jupyterhub_ceph_docker_volume_driver_alias }}" \
          LOG_LEVEL=1 \
          RBD_CONF_POOL="{{ jupyterhub_ceph_pool }}" \
          RBD_CONF_CLUSTER="{{ jupyterhub_ceph_cluster }}" \
          RBD_CONF_KEYRING_USER="{{ jupyterhub_ceph_client }}"
      when: docker_plugin_list.stdout | join ('') is not search(jupyterhub_ceph_docker_volume_driver_alias)