---
- name: Pull JupyterHub images.
  docker_image:
    name: "{{ item }}"
    force: yes
  loop:
    - "{{ jupyterhub_docker_image }}"
    - "{{ jupyterhub_db_docker_image }}"
    - "{{ jupyterhub_notebook_docker_image }}"
  tags:
    - pull

- name: Create Docker network.
  docker_network:
    name: "{{ jupyterhub_docker_network }}"
    ipam_config:
      - subnet: "{{ jupyterhub_docker_network_subnet }}"

- name: Configure JupyterHub.
  block:
    - name: Create JupyterHub config directory
      file:
        name: "{{ jupyterhub_config_path }}"
        state: directory
    - name: Create JupyterHub service environment configuration.
      template:
        src: "jupyterhub.env.j2"
        dest: "{{ jupyterhub_config_path }}/jupyterhub.env"
        mode: "0640"
      notify:
        - restart jupyterhub
    - name: Configure JupyterHub systemd service.
      template:
        src: jupyterhub.service.j2
        dest: "/etc/systemd/system/{{ jupyterhub_service_name }}.service"
      notify:
        - restart jupyterhub
    - name: Create database service environment configuration.
      template:
        src: "jupyterhub-db.env.j2"
        dest: "{{ jupyterhub_config_path }}/jupyterhub-db.env"
        mode: "0640"
      notify:
        - restart jupyterhub db
    - name: Configure database systemd service.
      template:
        src: jupyterhub-db.service.j2
        dest: "/etc/systemd/system/{{ jupyterhub_db_service_name }}.service"
      notify:
        - restart jupyterhub db
  tags:
    - configuration

- include_tasks: ceph.yml
  when: jupyterhub_enable_ceph | bool

- name: Enable JupyterHub services on boot.
  systemd:
    service: "{{ item }}"
    # TODO: this is a thorny part of ansible and we shouldn't have to do this ourselves.
    daemon_reload: yes
    state: started
    enabled: yes
  loop:
    - "{{ jupyterhub_service_name }}"
    - "{{ jupyterhub_db_service_name }}"
