---
docker_registry_image: registry:2
docker_registry_config_path: /etc/docker/registry
docker_registry_hostname: docker.chameleoncloud.org
docker_registry_port: 5000
docker_registry_debug_port: 5001
docker_registry_service_name: docker_registry
docker_registry_docker_network: registry
docker_registry_docker_network_subnet: 172.18.5.0/29
docker_registry_readonly_user: registry
docker_registry_readonly_password: ''

docker_registry_push_users:
  - hammock
  - jakecoll
  - jason_a
  - rochaa
  - zzhen
  - kolla

# Swift storage backend configuration
docker_registry_swift_username: docker_registry
docker_registry_swift_password: ''
docker_registry_swift_create_user: False
docker_registry_swift_authurl: https://chi.uc.chameleoncloud.org:5000/v3
docker_registry_swift_domain: default
docker_registry_swift_tenant: services
docker_registry_swift_region: CHI@UC
docker_registry_swift_containername: docker_registry
docker_registry_swift_endpointtype: internal

docker_registry_tasks:
  docker_registry_gc:
    group: docker_registry
    # Weekly on Tuesday at 5AM; mid-week to allow time to catch issues.
    calendar: "0 5 * * 2"
    command: /usr/local/sbin/docker-registry-gc
