---
precis_config_path: /etc/experiment-precis
precis_docker_network: experiment-precis
precis_docker_network_subnet: 172.18.10.0/24
# Corresponds to the default user 1001 used in s2i builds
precis_user: 1001

precis_rabbitmq_host: "{{ kolla_internal_vip_address }}"
precis_rabbitmq_inventory_group: rabbitmq
precis_rabbitmq_user: exp_precis
# precis_rabbitmq_password: ''
precis_rabbitmq_listener_queue: experiment_precis_event_queue
precis_rabbitmq_listener_bindings:
  - heat
  - ironic
  - neutron
  - nova
  - openstack
  - glance
precis_rabbitmq_rpc_queue: experiment_precis_service_queue

precis_mysql_host: "{{ kolla_internal_vip_address }}"
precis_mysql_inventory_group: mariadb
precis_mysql_database: experiment_precis
precis_mysql_user: exp_precis
# precis_mysql_password: ''
precis_mysql_external_database_privileges:
  - blazar.*:SELECT
  - glance.*:SELECT
  - heat.*:SELECT
  - neutron.*:SELECT
  - nova.*:SELECT
  - nova_api.*:SELECT

precis_init_docker_image: ghcr.io/chameleoncloud/experiment-precis/init:latest

precis_event_listener_docker_image: ghcr.io/chameleoncloud/experiment-precis/event-listener:latest
precis_event_listener_service_name: experiment-precis-event-listener
precis_event_listener_prometheus_port: 8913

precis_endpoint_docker_image: ghcr.io/chameleoncloud/experiment-precis/endpoint:latest
precis_endpoint_service_name: experiment-precis-endpoint
precis_endpoint_bind_interface: "{{ network_interface }}"
precis_endpoint_port: 8910

precis_generator_docker_image: ghcr.io/chameleoncloud/experiment-precis/generator:latest
precis_generator_service_name: experiment-precis-generator
precis_generator_prometheus_port: 8912

precis_cleanup_docker_image: ghcr.io/chameleoncloud/experiment-precis/cleanup:latest

precis_services:
  precis:
    group: precis
    enabled: "{{ enable_precis }}"
    haproxy:
      precis:
        enabled: true
        mode: "http"
        port: "{{ precis_endpoint_port }}"
        listen_port: "{{ precis_endpoint_port }}"
      precis_external:
        enabled: true
        mode: "http"
        external: true
        port: "{{ precis_endpoint_port }}"
        listen_port: "{{ precis_endpoint_port }}"
