---
- name: Create virtualenv.
  block:
    - name: Create virtualenv directory.
      file:
        path: "{{ pip_virtualenv }}"
        state: directory
    - name: Install virtualenv.
      package:
        name: python-virtualenv
        state: present
    - name: Install latest pip.
      pip:
        name: pip
        state: latest
        virtualenv: "{{ pip_virtualenv }}"
        virtualenv_site_packages: yes
