---
- name: Pull Docker image.
  docker_image:
    source: pull
    name: "{{ hammers_docker_image }}"
    force_source: yes

- name: Create config directory.
  file:
    path: "{{ hammers_config_path }}"
    state: directory

- name: Configure Hammers docker bash wrapper
  template:
    src: cc-hammer.j2
    mode: a+x
    dest: /usr/local/sbin/cc-hammer

- name: Configure Hammers env file
  template:
    src: hammers.env.j2
    mode: 0600
    dest: "{{ hammers_env_file }}"

- name: Configure slack webhook file
  template:
    src: slack.json.j2
    mode: 0600
    dest: "{{ hammers_config_path }}/slack.json"

- name: Create MySQL user
  local_action:
    module: mysql_user
    login_host: "{{ database_address }}"
    login_password: "{{ database_password }}"
    name: "{{ hammers_mysql_user }}"
    host: "%"
    password: "{{ hammers_mysql_password }}"
    priv: "*.*:SELECT,UPDATE,DELETE"

- name: Configure Hammers my.cnf
  template:
    src: my.cnf.j2
    dest: "{{ hammers_config_path }}/my.cnf"
  vars:
    mysql_host: "{{ hammers_mysql_host }}"

- name: Add hammer periodic tasks.
  include_role:
    name: diurnalist.periodic_task
  vars:
    task_name: "hammer_{{ item.key }}"
    task_command: "/usr/local/sbin/cc-hammer {{ item.value.cmd }}"
    task_calendar: "{{ item.value.calendar }}"
  loop: "{{ hammers | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
