---
- name: Authenticate to Docker registry
  become: True
  docker_login:
    registry_url: "{{ docker_registry }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"

- name: Pull Docker image.
  become: True
  docker_image:
    source: pull
    name: "{{ hammers_docker_image }}"
    force_source: yes

- name: Create config directory.
  become: yes
  file:
    path: "{{ hammers_config_path }}"
    state: directory

- name: Configure Hammers docker bash wrapper
  become: yes
  template:
    src: cc-hammer.j2
    mode: a+x
    dest: /usr/local/sbin/cc-hammer

- name: Configure Hammers env file
  become: yes
  template:
    src: hammers.env.j2
    mode: 0600
    dest: "{{ hammers_env_file }}"

- name: Configure slack webhook file
  become: yes
  template:
    src: slack.json.j2
    mode: 0600
    dest: "{{ hammers_config_path }}/slack.json"

- name: Create MySQL user
  become: True
  kolla_toolbox:
    module_name: mysql_user
    module_args:
      login_host: "{{ database_address }}"
      login_password: "{{ database_password }}"
      login_user: "{{ database_user }}"
      name: "{{ hammers_mysql_user }}"
      host: "%"
      password: "{{ hammers_mysql_password }}"
      priv: "*.*:SELECT,UPDATE,DELETE"
  run_once: True
  delegate_to: "{{ groups['hammers'][0] }}"

- name: Configure Hammers my.cnf
  become: yes
  template:
    src: my.cnf.j2
    dest: "{{ hammers_config_path }}/my.cnf"
  vars:
    mysql_host: "{{ hammers_mysql_host }}"

- name: Add hammer periodic tasks.
  include_role:
    name: chameleon.periodic_task
    apply:
      become: yes
  vars:
    task_name: "hammer_{{ item.key }}"
    task_command: "/usr/local/sbin/cc-hammer {{ item.value.cmd }}"
    task_calendar: "{{ item.value.calendar }}"
    task_enabled: "{{ item.value.enabled | bool }}"
  loop: "{{ hammers | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
