---
- name: Add reference API container to inventory.
  add_host:
    name: chameleon_referenceapi_1
    ansible_connection: docker
  changed_when: false

- name: Update reference repository inside reference API container.
  delegate_to: chameleon_referenceapi_1
  command: |
    cd /var/db/g5k-api/reference-repository \
      && git fetch \
      && git pull
