groups:
  - name: cron
    rules:
      - alert: CronJobNoRecentSuccess
        expr: |
          time() - cron_last_success
          > on (name) group_left() (
            cron_last_success_threshold
            or on (name) (
              count by (name)(cron_last_success) * 0 + (3600 * 25)
            )
          )
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.name }} cron job has not succeeded in more than 24 hours."
          description: "{{ $labels.name }} last succeeded {{ humanizeDuration $value }} ago and is likely failing."
          runbook: https://github.com/ChameleonCloud/chi-in-a-box/wiki/%5BRunbook%5D-CronJobNoRecentSuccess

  - name: periodic_task
    rules:
      - alert: PeriodicTaskNoRecentSuccess
        expr: |
          time() - periodic_task_last_success
          > on (name) group_left() (
            periodic_task_last_success_threshold
            or on (name) (
              count by (name)(periodic_task_last_success) * 0 + (3600 * 25)
            )
          )
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.name }} periodic task has not succeeded in more than 24 hours."
          description: "{{ $labels.name }} last succeeded {{ humanizeDuration $value }} ago and is likely failing."
          runbook: https://github.com/ChameleonCloud/chi-in-a-box/wiki/%5BRunbook%5D-PeriodicTaskNoRecentSuccess
