groups:
- name: mysql
  rules:

  - alert: MySQLHostDown
    expr: mysql_up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "The MySQL server at {{ $labels.hostname }} cannot be reached"
      description: "The MySQL exporter can not contact the MySQL server on {{ $labels.hostname }}. The MySQL server may not be running."
      runbook: https://github.com/ChameleonCloud/chi-in-a-box/wiki/%5BRunbook%5D-MySQLHostDown
