---

usage_collector_image: ghcr.io/chameleoncloud/usage-exploration
usage_collector_tag: latest
usage_collector_image_full: "{{ usage_collector_image }}:{{ usage_collector_tag }}"

usage_collector_config_dir: /etc/chameleon_usage_collector
usage_collector_timer: "*-*-* 00:00:00" # collect daily at midnight

usage_collector_site_key: "{{ chameleon_site_name }}" # from defaults.yml or site-config
usage_collector_site_name: "{{ openstack_region_name }}"

usage_collector_mysql_user: cc_usage # Read only user
#usage_collector_mysql_password:

usage_collector_db_uri: "mysql://{{ usage_collector_mysql_user }}:{{ usage_collector_mysql_password }}@{{ database_address }}"

# usage_collector_data_dir:  # path to save exported data. May start with s3://
usage_collector_s3_endpoint: https://chi.uc.chameleoncloud.org:7480
# usage_collector_s3_access_key_id:
# usage_collector_secret_access_key:

usage_collector_manage_mysql_grants: true

usage_collector_mysql_grants:
  - nova.compute_nodes:SELECT
  - nova.instances:SELECT
  - nova.instance_actions:SELECT
  - nova.instance_actions_events:SELECT
  - nova_api.request_specs:SELECT
  - blazar.computehosts:SELECT
  - blazar.computehost_allocations:SELECT
  - blazar.reservations:SELECT
  - blazar.instance_reservations:SELECT
  - blazar.leases:SELECT
  - blazar.devices:SELECT
  - blazar.device_allocations:SELECT
  - blazar.device_extra_capabilities:SELECT
  - blazar.device_reservations:SELECT
  - zun.container:SELECT
  - zun.container_actions:SELECT
  - zun.container_actions_events:SELECT
  - chameleon_usage.node_usage_report_cache:SELECT
  - chameleon_usage.node_count_cache:SELECT
  - chameleon_usage.node_usage:SELECT
  - chameleon_usage.node_event:SELECT
  - chameleon_usage.node_maintenance:SELECT
  - openstack_audit.audit_blazar_computehosts:SELECT
  - openstack_audit.audit_blazar_computehost_extra_capabilities:SELECT
  - openstack_audit.audit_blazar_resource_properties:SELECT
  - openstack_audit.audit_nova_compute_nodes:SELECT
  - openstack_audit.audit_nova_services:SELECT
  - openstack_audit.audit_nova_instances:SELECT
  - openstack_audit.audit_nova_instance_actions:SELECT
  - openstack_audit.audit_nova_instance_actions_events:SELECT
  - openstack_audit.audit_ironic_nodes:SELECT
