---
- name: reload systemd daemon
  service:
    daemon_reload: yes

- name: restart prometheus
  service:
    name: prometheus_server
    state: restarted

- name: restart alertmanager
  service:
    name: prometheus_alertmanager
    state: restarted

- name: restart ceph exporter
  service:
    name: prometheus_ceph_exporter
    state: restarted

- name: restart mysql exporter
  service:
    name: prometheus_mysql_exporter
    state: restarted

- name: restart node exporter
  service:
    name: prometheus_node_exporter
    state: restarted

- name: restart openstack exporter
  service:
    name: prometheus_openstack_exporter
    state: restarted

- name: restart snmp exporter
  service:
    name: prometheus_snmp_exporter
    state: restarted

- name: restart pushgateway
  service:
    name: prometheus_pushgateway
    state: restarted

- name: restart redis exporter
  service:
    name: prometheus_redis_exporter
    state: restarted
