[chameleon-supported]
create = {{ glance_openstack_user }}
read   = @ # anyone can read
update = {{ glance_openstack_user }}
delete = {{ glance_openstack_user }}

# catch‑all for any other properties – allow
[.*]
create = @
read   = @
update = @
delete = @
