---
- name: Ensure Neutron configuration directories exist.
  file:
    name: "{{ item }}"
    state: directory
  loop:
    - "{{ node_custom_config }}/neutron"
    - "{{ node_custom_config }}/neutron/plugins"

- name: Copy Neutron configuration files.
  block:
    - copy:
        src: policy.json
        dest: "{{ node_custom_config }}/neutron/policy.json"
    - template:
        src: "ml2_genericswitch.conf.j2"
        dest: "{{ node_custom_config }}/neutron/plugins/ml2_genericswitch.conf"
