---
- name: Pull metric collector images.
  docker_image:
    name: "{{ metric_collector_docker_image }}"
    force: yes
  tags:
    - pull

- name: Set facts from global configuration.
  set_fact:
    metric_collector_corsa_switches: "{{ switch_configs | selectattr('device_type', 'match', '^corsa') | list }}"
  tags:
    - always

- name: Configure metric collector.
  block:
    - name: Create config directory.
      file:
        name: "{{ metric_collector_config_path }}"
        state: directory
    - name: Create configuration.
      template:
        src: "config.yml.j2"
        dest: "{{ metric_collector_config_path }}/config.yml"
        mode: "0640"
    - name: Configure systemd services.
      template:
        src: systemd.service.j2
        dest: "/usr/lib/systemd/system/{{ metric_collector_service_name }}@.service"
      notify:
        - reload systemd
        - restart metric collectors
  tags:
    - configuration

- name: Enable metric collector services on boot.
  systemd:
    service: "{{ metric_collector_service_name }}@{{ item.module_name }}"
    state: started
    enabled: yes
  when: item.condition
  loop:
    - module_name: switch_corsa
      condition: metric_collector_corsa_switches | length > 0
