---
- name: Pull Keycloak TAS sync task images.
  docker_image:
    source: pull
    name: "{{ item.value.docker.image }}"
    force_source: yes
  loop: "{{ keycloak_tas_sync_tasks|dict2items }}"
  loop_control:
    label: "{{ (item.value.docker | default({})).image|default(None) }}"
  when:
    - item.value.docker is defined
    - inventory_hostname in groups[item.value.group]
  tags:
    - pull

- name: Configure Keycloak TAS sync periodic tasks.
  include_role:
    name: chameleon.periodic_task
  vars:
    task_name: "{{ item.key }}"
    task_calendar: "{{ item.value.calendar }}"
    task_command: "{{ item.value.command|default(None) }}"
    task_docker: "{{ item.value.docker|default(None) }}"
  loop: "{{ keycloak_tas_sync_tasks|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - inventory_hostname in groups[item.value.group]
