[DEFAULT]

# CHAMELEON HACK: Blazar does a single, non-paginated GET /v3/users. In 2025.1,
# keystone applies a default max_db_limit of 1000. Override to a large number 
# until blazar uses pagination for this query.

# As a query can potentially return many thousands of items, you can limit the
# maximum number of items in a single response by setting this option. While
# `list_limit` is used to set the default page size this parameter sets global
# maximum that cannot be exceded. (integer value)
# Minimum value: 0
#max_db_limit = 1000
max_db_limit = 100000


[auth]
methods = password,token,openid,external,application_credential

[mapped]
# Automatically remove users from projects when they lose their membership
remove_dangling_assignments = True

[security_compliance]
allow_insecure_application_credential_trust_escalation = {{ keystone_allow_insecure_application_credential_trust_escalation | bool}}
