[DEFAULT]

# tokens from federated auth are always length 268, > default of 255
max_token_size = 269

[auth]
methods = password,token,openid,external,application_credential

[mapped]
# Automatically remove users from projects when they lose their membership
remove_dangling_assignments = True
