[DEFAULT]

[auth]
methods = password,token,openid,external,application_credential

[mapped]
# Automatically remove users from projects when they lose their membership
remove_dangling_assignments = True

[security_compliance]
allow_insecure_application_credential_trust_escalation = {{ keystone_allow_insecure_application_credential_trust_escalation | bool}}
