---
- name: Create freepool aggregate.
  kolla_toolbox:
    module_name: os_nova_host_aggregate
    module_args:
      auth: "{{ openstack_auth }}"
      state: present
      name: freepool
  run_once: True
  when: enable_blazar | bool
