---
- name: configure predefined networks
  include_tasks: config-network.yml
  tags: [neutron]
  loop: "{{ neutron_networks }}"
  loop_control:
    label: "{{ item.name }}"
- name: configure sharednet router
  tags: [neutron]
  include_tasks: sharednet-router.yml
