---
- name: Configure public network
  include_tasks: create_network.yml
  vars:
    network_name: public
    network_args:
      project: "{{ keystone_admin_project }}"
      provider_network_type: flat
      provider_physical_network: public
      external: yes
  when: public_network is defined

- name: Set fact for public allocation pool
  set_fact:
    public_allocation_pool_start: "{{ public_network.allocation_pools[0].start | default(public_network.cidr | next_nth_usable(2)) }}"
    public_allocation_pool_end: "{{ public_network.allocation_pools[0].end | default(public_network.cidr | ipaddr('last_usable') | ipmath(-1)) }}"
  when:
    - public_network is defined
    - public_network.cidr is defined

- name: Configure public subnet
  include_tasks: create_subnet.yml
  vars:
    subnet_name: public-subnet
    subnet_args:
      project: "{{ keystone_admin_project }}"
      network_name: public
      cidr: "{{ public_network.cidr }}"
      enable_dhcp: false
      gateway_ip: "{{ public_network.gateway_ip | default(public_network.cidr | ipaddr('last_usable')) }}"
      allocation_pool_start: "{{ public_allocation_pool_start }}"
      allocation_pool_end: "{{ public_allocation_pool_end }}"
  when:
    - public_network is defined
    - public_network.cidr is defined