---
- ansible.builtin.file:
    name: "{{ k3s_conf_location }}/calico"
    state: directory

- name: Download Calico release
  ansible.builtin.get_url:
    url: "https://github.com/projectcalico/calico/releases/download/{{ k3s_calico_version }}/release-{{ k3s_calico_version }}.tgz"
    dest: "{{ k3s_conf_location }}/calico/release-{{ k3s_calico_version }}.tgz"
    owner: root
    group: root
    mode: 0755

- name: Unpack Calico release
  ansible.builtin.unarchive:
    src: "{{ k3s_conf_location }}/calico/release-{{ k3s_calico_version }}.tgz"
    dest: "{{ k3s_conf_location }}/calico/"
    creates: "{{ k3s_conf_location }}/calico/release-{{ k3s_calico_version }}"
  register: calico_release

- name: Update Calico operator
  command: >-
    kubectl apply -f {{ calico_release.dest }}/manifests/tigera-operator.yaml
  when:
    - calico_release.changed

- name: Install calicoctl
  ansible.builtin.copy:
    # TODO: use facts to optionally install ARM or otherwise
    src: "{{ calico_release.dest }}/bin/calicoctl/calicoctl-linux-amd64"
    remote_src: yes
    dest: /usr/local/bin/kubectl-calico
  when:
    - calico_release.changed

- name: Generate Calico custom resources
  ansible.builtin.template:
    src: "calico-custom-resources.yaml.j2"
    dest: "{{ k3s_conf_location }}/calico-custom-resources.yaml"
    owner: root
    group: root
    mode: 0644
  register: calico_custom_resources

- name: Create Calico custom resources
  command: >-
    kubectl apply -f {{ calico_custom_resources.dest }}
  when:
    - calico_custom_resources.changed

- name: Generate Calico global network policies
  ansible.builtin.copy:
    src: "calico-global-networkpolicy-{{ item }}.yaml"
    dest: "{{ k3s_conf_location }}/calico-global-networkpolicy-{{ item }}.yaml"
    owner: root
    group: root
    mode: 0644
  loop:
    - default-deny
    - allow-ping

- name: Apply Calico global network policies
  command: >-
    kubectl apply -f {{ k3s_conf_location }}/calico-global-networkpolicy-{{ item }}.yaml
  loop:
    - default-deny
    - allow-ping
