---
# FUTURE NOTE: change all the kubectl invocations to use the kubernetes.core.k8s collection!
# This will make detecting changes way easier and more reliable.

- name: Checkout NVIDIA device plugin
  ansible.builtin.git:
    repo: "https://github.com/NVIDIA/k8s-device-plugin"
    dest: "{{ k3s_conf_location }}/nvidia-device-plugin"
    version: "{{ k3s_nvidia_device_plugin_version }}"
    update: yes
    force: yes
  register: nvidia_device_plugin_release

- name: Update Calico operator
  command: >-
    kubectl apply -f {{ k3s_conf_location }}/nvidia-device-plugin/nvidia-device-plugin.yml
  when:
    - nvidia_device_plugin_release.changed

- name: Template daemonsets for smarter-device plugins
  ansible.builtin.template:
    src: "smarter-device-manager-ds-{{ item }}.yaml.j2"
    dest: "{{ k3s_conf_location }}/smarter-device-manager-ds-{{ item }}.yaml"
    owner: root
    group: root
    mode: "0644"
  loop:
    - jetson
    - rpi

- name: Apply configsets for rpi and xavier
  command: >-
    kubectl apply -f {{ k3s_conf_location }}/smarter-device-manager-ds-{{ item }}.yaml
  loop:
    - jetson
    - rpi
