---
# FUTURE NOTE: change all the kubectl invocations to use the kubernetes.core.k8s collection!
# This will make detecting changes way easier and more reliable.

- name: Copy nvidia device plugin daemonset config
  ansible.builtin.copy:
    src: nvidia-device-plugin.yaml
    dest: "{{ k3s_conf_locagion/nvidia-device-plugin.yaml"
    owner: root
    group: root
    mode: "0644"
  register: nvidia_device_plugin

- name: Update nvidia device plugin daemonset
  command: >-
    kubectl apply -f {{ k3s_conf_location }}/nvidia-device-plugin.yaml
  when:
    - nvidia_device_plugin.changed

- name: Template daemonsets for smarter-device plugins
  ansible.builtin.template:
    src: "smarter-device-manager-ds-{{ item }}.yaml.j2"
    dest: "{{ k3s_conf_location }}/smarter-device-manager-ds-{{ item }}.yaml"
    owner: root
    group: root
    mode: "0644"
  loop:
    - jetson
    - rpi

- name: Apply configsets for rpi and xavier
  command: >-
    kubectl apply -f {{ k3s_conf_location }}/smarter-device-manager-ds-{{ item }}.yaml
  loop:
    - jetson
    - rpi
