---
- name: Create calico network
  tags: [neutron]
  kolla_toolbox:
    module_name: openstack.cloud.network
    module_args:
      auth: "{{ openstack_auth }}"
      project: "{{ keystone_admin_project_name }}"
      name: "{{calico_network_name}}"
      provider_network_type: flat
      provider_physical_network: calico
      shared: yes
      state: present
  run_once: true

- name: Create calico subnet
  tags: [neutron]
  kolla_toolbox:
    module_name: openstack.cloud.subnet
    module_args:
      auth: "{{ openstack_auth }}"
      project: "{{ keystone_admin_project_name }}"
      network_name: "{{calico_network_name}}"
      name: "{{calico_subnet_name}}"
      cidr: "{{ k3s_cluster_cidr }}"
      enable_dhcp: no
      state: present
  register: subnet_result

- name: Get sharednet-router info
  tags: [neutron]
  kolla_toolbox:
    module_name: openstack.cloud.routers_info
    module_args:
      auth: "{{ openstack_auth }}"
      name: "{{ sharednet_router_name }}"
  register: router_result

- name: get list of needed interfaces
  tags: [neutron]
  vars:
    current_router_interfaces: "{{ router_result.openstack_routers[0].interfaces_info }}"
    subnet_id: "{{ subnet_result.subnet.id }}"
  set_fact:
    attached_subnet_ids: "{{ ((current_router_interfaces | map(attribute='subnet_id') | list) + [subnet_id]) | unique }}"

- name: ensure default router has port for calico
  tags: [neutron]
  kolla_toolbox:
    module_name: openstack.cloud.router
    module_args:
      auth: "{{ openstack_auth }}"
      project: "{{ keystone_admin_project }}"
      name: "{{ sharednet_router_name }}"
      state: present
      interfaces: "{{ attached_subnet_ids }}"

- name: Generate Calico/Neutron connection script
  ansible.builtin.template:
    src: neutron-calico-connect.j2
    dest: "{{ k3s_conf_location }}/neutron-calico-connect.sh"
    owner: root
    group: root
    mode: "0700"
  vars:
    neutron_router_id: "{{ calico_router.router.id }}"
  when:
    - k3s_enable_calico | bool
