---
- name: Checkout NVIDIA device plugin
  ansible.builtin.git:
    repo: "https://github.com/NVIDIA/k8s-device-plugin"
    dest: "{{ k3s_conf_location }}/nvidia-device-plugin"
    version: "{{ k3s_nvidia_device_plugin_version }}"
    update: yes
    force: yes
  register: nvidia_device_plugin_release

- name: Update Calico operator
  command: >-
    kubectl apply -f {{ k3s_conf_location }}/nvidia-device-plugin/nvidia-device-plugin.yml
  when:
    - nvidia_device_plugin_release.changed

- name: Checkout smarter-device device plugin
  ansible.builtin.git:
    repo: "https://gitlab.com/arm-research/smarter/smarter-device-manager"
    dest: "{{ k3s_conf_location }}/smarter-device-manager"
    version: "{{ k3s_smarter_device_plugin_version }}"
    update: yes
    force: yes
  register: smarter_device_plugin_release

- name: Replace namespace placeholder for smarter-device daemonset
  ansible.builtin.replace:
    path: "{{ k3s_conf_location }}/smarter-device-manager/smarter-device-manager-ds.yaml"
    regexp: "< Replace with the namespace to use >"
    replace: "smarter-device-manager-system"
  when:
    - smarter_device_plugin_release.changed

- name: Apply smarter-device device plugin
  command: >-
    kubectl apply -f {{ k3s_conf_location }}/smarter-device-manager/smarter-device-manager-ds.yaml
  when:
    - smarter_device_plugin_release.changed
