---
- name: Create config directory.
  become: true
  file:
    path: "{{ hammers_config_path }}"
    state: directory

- name: Configure Hammers env file
  become: true
  template:
    src: hammers.env.j2
    mode: 0600
    dest: "{{ hammers_env_file }}"

- name: Configure slack webhook file
  become: true
  template:
    src: slack.json.j2
    mode: 0600
    dest: "{{ hammers_config_path }}/slack.json"
  when: hammers_slack_webhook is defined

- name: Install hammers_v2 systemd units
  include_tasks: install_unit.yml
  vars:
    service_name: "hammer_{{ item.key }}"
    timer_state: "{{ 'started' if item.value.enabled else 'stopped' }}"
    timer_enabled: "{{item.value.enabled}}"
  loop: "{{ hammers_v2 | dict2items }}"
