---
- name: Pull Docker image.
  docker_image:
    source: pull
    name: "{{ chameleon_usage_docker_image }}"
    force_source: yes

- name: Create config directory.
  file:
    path: "{{ chameleon_usage_config_dir }}"
    state: directory
    
- name: Configure my.cnf
  template:
    src: my.cnf.j2
    dest: "{{ chameleon_usage_config_dir }}/my.cnf"
  vars:
    mysql_host: "{{ chameleon_usage_mysql_host }}"
    root_password: "{{ database_password }}"
