---
- name: Copy Google Analytics key
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ chameleon_usage_config_dir }}/google-analytics-key.json"
  with_first_found:
    - "{{ node_custom_config }}/chameleon_usage/{{ inventory_hostname }}/google-analytics-key.json"
    - "{{ node_custom_config }}/chameleon_usage/google-analytics-key.json"

- name: Configure chameleon usage heat template download docker bash wapper
  become: yes
  template:
    src:  chameleon-usage-heat-template-downloads.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-heat-template-downloads

- name: Fill in up-to-date data to chameleon_usage
  become: yes
  command: "/usr/local/sbin/chameleon-usage-heat-template-downloads"

- name: Set up Heat downloads periodic task
  include_role:
    name: chameleon.periodic_task
  vars:
    task_name: "usage_heat_template_downloads"
    task_command: "/usr/local/sbin/chameleon-usage-heat-template-downloads"
    task_calendar: "05:00"
