---
- name: Configure chameleon usage heat template download docker bash wapper
  template:
    src:  chameleon-usage-heat-template-downloads.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-heat-template-downloads

- name: Fill in up-to-date data to chameleon_usage
  command: "/usr/local/sbin/chameleon-usage-heat-template-downloads"

- name: Set up Heat downloads periodic task
  include_role:
    name: chameleon.periodic_task
  vars:
    task_name: "usage_heat_template_downloads"
    task_command: "/usr/local/sbin/chameleon-usage-heat-template-downloads"
    task_calendar: "* 5 * * *"
