---
- name: Configure chameleon jupyter usage docker bash wapper
  template:
    src:  chameleon-usage-jupyter.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-jupyter

- name: Fill in current data to chameleon_usage
  command: "/usr/local/sbin/chameleon-usage-jupyter"

- name: Set up Jupyter usage periodic task
  include_role:
    name: chameleon.periodic_task
  vars:
    task_name: "usage_jupyter"
    task_command: "/usr/local/sbin/chameleon-usage-jupyter"
    task_calendar: "*/5 * * * *"

- name: Configure chameleon jupyter usage report cache docker bash wrapper
  template:
    src: chameleon-usage-jupyter-usage-report-cache.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-jupyter-usage-report-cache

- name: Create jupyter usage report cache table and fill in data
  command: "/usr/local/sbin/chameleon-usage-jupyter-usage-report-cache"

- name: Set up Jupyter usage cache periodic task
  include_role:
    name: chameleon.periodic_task
  vars:
    task_name: "usage_jupyter_report_cache"
    task_command: "/usr/local/sbin/chameleon-usage-jupyter-usage-report-cache"
    task_calendar: "* 6 * * *"
