---
- name: Pull Docker image.
  docker_image:
    source: pull
    name: "{{ chameleon_usage_docker_image }}"
    force: yes
    
- name: Create config directory.
  file:
    path: "{{ chameleon_usage_config_dir }}"
    state: directory
    
- name: Create MySQL user
  local_action:
    module: mysql_user
    login_host: "{{ groups.mariadb[0] }}"
    login_password: "{{ database_password }}"
    name: "{{ chameleon_usage_mysql_user }}"
    host: "%"
    password: "{{ chameleon_usage_mysql_password }}"
    priv: "{{ item }}"
    append_privs: 'yes'
  with_items:
    - 'blazar_backup\_%.*:CREATE,DROP,SELECT,INSERT'
    - 'keystone_backup\_%.*:CREATE,DROP,SELECT,INSERT'
    - 'nova_backup\_%.*:CREATE,DROP,SELECT,INSERT'
    - 'ironic_backup\_%.*:CREATE,DROP,SELECT,INSERT'
    - 'chameleon_usage.*:CREATE,SELECT,INSERT,UPDATE,DELETE'
    
- name: Configure my.cnf
  template:
    src: my.cnf.j2
    dest: "{{ chameleon_usage_config_dir }}/my.cnf"
  vars:
    mysql_host: "{{ chameleon_usage_mysql_host }}"
    root_password: "{{ database_password }}"
    
- name: Initialize chameleon_usage database
  shell: |
    docker run --rm --net=host \
    -v "{{ chameleon_usage_config_dir }}/my.cnf:/etc/mysql/my.cnf" \
    {{ chameleon_usage_docker_image }} setup_database --mysql-conf /etc/mysql/my.cnf 2>&1
    
- name: Configure chameleon usage data extract docker bash wrapper
  template:
    src: chameleon-usage-extract-data.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-extract-data
    
- name: Fill in up-to-date data to chameleon_usage
  command: "/usr/local/sbin/chameleon-usage-extract-data"

- name: Set up data extract cron job
  cron:
    name: "chameleon_usage"
    minute: "0"
    hour: "6"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/local/sbin/chameleon-usage-extract-data | /usr/bin/logger -t \"chameleon_usage\""
    
- name: Configure chameleon usage heat template download docker bash wapper
  when: enable_usage_appliance_report
  template:
    src:  chameleon-usage-heat-template-downloads.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-heat-template-downloads
    
- name: Fill in up-to-date data to chameleon_usage
  when: enable_usage_appliance_report
  command: "/usr/local/sbin/chameleon-usage-heat-template-downloads"
  
- name: Set up heat template downloads cron job
  when: enable_usage_appliance_report
  cron:
    name: "heat_template_downloads"
    minute: "0"
    hour: "5"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/local/sbin/chameleon-usage-heat-template-downloads | /usr/bin/logger -t \"heat_template_downloads\""
