--- 
- name: Pull Docker image.
  docker_image:
    source: pull
    name: "{{ chameleon_usage_docker_image }}"
    force_source: yes

- name: Create config directory.
  file:
    path: "{{ chameleon_usage_config_dir }}"
    state: directory
    
- name: Configure my.cnf
  template:
    src: my.cnf.j2
    dest: "{{ chameleon_usage_config_dir }}/my.cnf"
  vars:
    mysql_host: "{{ chameleon_usage_mysql_host }}"
    root_password: "{{ database_password }}"

- name: Create MySQL user
  local_action:
    module: mysql_user
    login_host: "{{ groups.mariadb[0] }}"
    login_password: "{{ database_password }}"
    name: "{{ chameleon_usage_mysql_user }}"
    host: "%"
    password: "{{ chameleon_usage_mysql_password }}"
    priv: "{{ item }}"
    append_privs: 'yes'
  with_items:
    - 'chameleon_usage.*:CREATE,SELECT,INSERT,UPDATE,DELETE'
    - 'nova.*:SELECT'
    - 'keystone.*:SELECT'
    
- name: Initialize chameleon_usage database
  shell: |
    docker run --rm --net=host \
    -v "{{ chameleon_usage_config_dir }}/my.cnf:/etc/mysql/my.cnf" \
    {{ chameleon_usage_docker_image }} setup_database --mysql-conf /etc/mysql/my.cnf 2>&1

- name: Configure chameleon usage data extract docker bash wrapper
  template:
    src: chameleon-usage-extract-data.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-extract-kvm-data

- name: Fill in up-to-date data to chameleon_usage
  command: "/usr/local/sbin/chameleon-usage-extract-kvm-data"

- name: Set up node data extract periodic task
  include_role:
    name: chameleon.periodic_task
  vars:
    task_name: "kvm_usage"
    task_command: "/usr/local/sbin/chameleon-usage-extract-kvm-data"
    task_calendar: "09:00"
