---
- name: Create MySQL user
  kolla_toolbox:
    module_name: mysql_user
    module_args:
      login_host: "{{ database_address }}"
      login_password: "{{ database_password }}"
      login_user: "{{ database_user }}"
      name: "{{ chameleon_usage_mysql_user }}"
      host: "%"
      password: "{{ chameleon_usage_mysql_password }}"
      priv: "{{ item }}"
      append_privs: yes
  run_once: True
  delegate_to: "{{ groups['hammers'][0] }}"
  loop:
    - 'blazar_backup\_%.*:CREATE,DROP,SELECT,INSERT'
    - 'keystone_backup\_%.*:CREATE,DROP,SELECT,INSERT'
    - 'nova_backup\_%.*:CREATE,DROP,SELECT,INSERT'
    - 'ironic_backup\_%.*:CREATE,DROP,SELECT,INSERT'
    - 'chameleon_usage.*:CREATE,SELECT,INSERT,UPDATE,DELETE'
    - 'blazar.*:SELECT'
    - 'ironic.*:SELECT'

- name: Initialize chameleon_usage database
  shell: |
    docker run --rm --net=host \
    -v "{{ chameleon_usage_config_dir }}/my.cnf:/etc/mysql/my.cnf" \
    {{ chameleon_usage_docker_image }} setup_database --mysql-conf /etc/mysql/my.cnf 2>&1
