---
- name: Configure chameleon usage data extract docker bash wrapper
  template:
    src: chameleon-usage-extract-data.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-extract-data
    
- name: Fill in up-to-date data to chameleon_usage
  command: "/usr/local/sbin/chameleon-usage-extract-data"

- name: Set up data extract cron job
  cron:
    name: "chameleon_usage"
    minute: "0"
    hour: "9"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/local/sbin/chameleon-usage-extract-data | /usr/bin/logger -t \"chameleon_usage\""

- name: Configure slack webhook file
  template:
    src: slack.json.j2
    mode: 0600
    dest: "{{ chameleon_usage_config_dir }}/slack.json"

- name: Configure chameleon node usage sanity checks docker bash wrapper
  template:
    src: chameleon-usage-sanity-checks.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-sanity-checks
    
- name: Set up data extract cron job
  cron:
    name: "chameleon_usage_sanity_checks"
    minute: "0"
    hour: "10"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/local/sbin/chameleon-usage-sanity-checks | /usr/bin/logger -t \"chameleon_usage_sanity_checks\""
