---
- name: Configure chameleon usage data extract docker bash wrapper
  template:
    src: chameleon-usage-extract-data.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-extract-data

- name: Fill in up-to-date data to chameleon_usage
  command: "/usr/local/sbin/chameleon-usage-extract-data"

- name: Set up node data extract periodic task
  include_role:
    name: chameleon.periodic_task
  vars:
    task_name: "usage_node"
    task_command: "/usr/local/sbin/chameleon-usage-extract-data"
    task_calendar: "06:00"

- name: Configure slack webhook file
  template:
    src: slack.json.j2
    mode: 0600
    dest: "{{ chameleon_usage_config_dir }}/slack.json"

- name: Configure chameleon node usage sanity checks docker bash wrapper
  template:
    src: chameleon-usage-sanity-checks.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-sanity-checks

- name: Set up node data sanity check periodic task
  include_role:
    name: chameleon.periodic_task
  vars:
    task_name: "usage_node_sanity"
    task_command: "/usr/local/sbin/chameleon-usage-sanity-checks"
    task_calendar: "10:00"
