---
- name: Place credentials file
  template:
    src: usage-credentials.j2
    mode: 0700
    dest: /usr/local/sbin/usage-credentials

- name: Place usage script
  template:
    src: /root/scripts/chameleon-usage-reporting/project_usage_collect/usage.py
    mode: 0700
    dest: /usr/local/sbin/usage.py

- name: Add glance backup cron jobs.
  cron:
    name: "{{ usage_report_cron_name }}"
    minute: "{{ usage_report_cron_minute }}"
    hour: "{{ usage_report_cron_hour }}"
    day: "{{ usage_report_cron_day }}"
    month: "{{ usage_report_cron_month }}"
    weekday: "{{ usage_report_cron_weekday }}"
    job: "source {{ usage_report_credentials }} && {{ usage_report_cron_script }} && {{ cron_notification }} usage_report"
