---
- name: Place credentials file
  template:
    src: user_project_report_credentials.j2
    mode: 0700
    dest: /usr/local/sbin/user_project_report_credentials

- name: Place usage script
  template:
    src: /root/scripts/chameleon-usage-reporting/project_usage_collect/user_project_report.py
    mode: 0700
    dest: /usr/local/sbin/user_project_report.py

- name: Add glance backup cron jobs.
  cron:
    name: "{{ user_project_report_cron_name }}"
    minute: "{{ user_project_report_cron_minute }}"
    hour: "{{ user_project_report_cron_hour }}"
    day: "{{ user_project_report_cron_day }}"
    month: "{{ user_project_report_cron_month }}"
    weekday: "{{ user_project_report_cron_weekday }}"
    job: "source {{ user_project_report_credentials }} && {{ user_project_report_cron_script }} && {{ cron_notification }} user_project_report"
