---
- name: Configure credentials file
  template:
    src: user_project_report_credentials.j2
    mode: 0700
    dest: "{{ chameleon_usage_config_dir }}/user_project_report_credentials"
  vars:
    mysql_host: "{{ chameleon_usage_mysql_host }}"

- name: Configure chameleon usage user project report docker bash wrapper
  template:
    src: chameleon-usage-user-project-report.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-user-project-report

- name: Set up user/project extract periodic task.
  include_role:
    name: chameleon.periodic_task
  vars:
    task_name: "usage_user_project"
    task_command: "/usr/local/sbin/chameleon-usage-user-project-report"
    task_calendar: "03:00"
