---
- name: Configure credentials file
  template:
    src: user_project_report_credentials.j2
    mode: 0700
    dest: "{{ chameleon_usage_config_dir }}/user_project_report_credentials"
  vars:
    mysql_host: "{{ chameleon_usage_mysql_host }}"

- name: Configure chameleon usage user project report docker bash wrapper
  template:
    src: chameleon-usage-user-project-report.j2
    mode: a+x
    dest: /usr/local/sbin/chameleon-usage-user-project-report

- name: Add glance backup cron jobs.
  cron:
    name: "{{ user_project_report_cron_name }}"
    minute: "0"
    hour: "3"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/local/sbin/chameleon-usage-user-project-report | /usr/bin/logger -t \"chameleon_usage_user_project\""
