---
- name: Place credentials file
  template:
    src: user_project_report_credentials.j2
    mode: 0700
    dest: /usr/local/sbin/user_project_report_credentials

- name: Place usage script
  template:
    src: /root/scripts/chameleon-usage-reporting/user_project/user_project_report.py
    mode: 0700
    dest: /usr/local/sbin/user_project_report.py

- name: Add glance backup cron jobs.
  cron:
    name: "{{ user_project_report_cron_name }}"
    minute: "0"
    hour: "3"
    day: "*"
    month: "*"
    weekday: "*"
    job: "source {{ user_project_report_credentials }} && {{ user_project_report_cron_script }} && {{ cron_notification }} user_project_report"
