---
jupyterhub_config_path: /etc/jupyterhub
jupyterhub_crypt_key:
jupyterhub_tag: 76a6fd9
jupyterhub_image_full: "docker.chameleoncloud.org/jupyterhub:{{ jupyterhub_tag }}"
jupyterhub_docker_network: jupyterhub
jupyterhub_docker_network_subnet: 172.18.20.0/24
jupyterhub_hostname: "{{ kolla_external_fqdn }}"
# Just needs to be something that doesn't conflict
jupyterhub_port: 8075
jupyterhub_auth: "{{ openstack_auth }}"

jupyterhub_db_user: jupyterhub
jupyterhub_db_db: jupyterhub

# NOTE(jason): this is declared separately because additional optional keys
# are added during the configuration task.
jupyterhub_environment:
  JUPYTERHUB_PUBLIC_URL: "https://{{ jupyterhub_hostname }}/"
  JUPYTERHUB_CRYPT_KEY: "{{ jupyterhub_crypt_key }}"
  DOCKER_NETWORK_NAME: "{{ jupyterhub_docker_network }}"
  DOCKER_NOTEBOOK_DIR: "{{ jupyterhub_notebook_workdir }}"
  DOCKER_NOTEBOOK_IMAGE: "{{ jupyterhub_notebook_image_full }}"
  KEYCLOAK_SERVER_URL: "{{ keycloak_url }}"
  KEYCLOAK_REALM_NAME: "{{ keycloak_realm_name }}"
  KEYCLOAK_CLIENT_ID: "{{ jupyterhub_keycloak_client_id }}"
  KEYCLOAK_CLIENT_SECRET: "{{ jupyterhub_keycloak_client_secret }}"
  MYSQL_HOST: jupyterhub_db
  MYSQL_USER: "{{ jupyterhub_db_user }}"
  MYSQL_PASSWORD: "{{ jupyterhub_db_password }}"
  MYSQL_DATABASE: "{{ jupyterhub_db_db }}"
  OS_AUTH_URL: "{{ keystone_public_url }}/v3"
  OS_REGION_NAME: "{{ openstack_region_name }}"
  OS_IDENTITY_PROVIDER: "{{ identity_provider_name }}"
  OS_PROTOCOL: openid
  OS_PROJECT_DOMAIN_NAME: "{{ identity_provider_domain_name }}"
  ARTIFACT_SHARING_OS_AUTH_TYPE: v3password
  ARTIFACT_SHARING_OS_USERNAME: "{{ jupyterhub_artifact_sharing_keystone_user }}"
  ARTIFACT_SHARING_OS_PASSWORD: "{{ jupyterhub_artifact_sharing_keystone_password }}"
  ARTIFACT_SHARING_OS_USER_DOMAIN_NAME: default
  ARTIFACT_SHARING_OS_PROJECT_NAME: service
  ARTIFACT_SHARING_OS_PROJECT_DOMAIN_NAME: default
  ARTIFACT_SHARING_SWIFT_ACCOUNT: "{{ jupyterhub_artifact_sharing_swift_account }}"
  ARTIFACT_SHARING_SWIFT_CONTAINER: "{{ jupyterhub_artifact_sharing_container }}"
  ARTIFACT_SHARING_SWIFT_TEMP_URL_KEY: "{{ jupyterhub_artifact_sharing_swift_temp_url_key }}"
  ARTIFACT_SHARING_TRUST_PROJECT_NAME: "{{ jupyterhub_artifact_sharing_keystone_trust_project_name }}"

jupyterhub_services:
  jupyterhub:
    group: jupyterhub
    enabled: true
    image: "{{ jupyterhub_image_full }}"
    network: "{{ jupyterhub_docker_network }}"
    environment: "{{ jupyterhub_environment }}"
    ports:
      - "{{ jupyterhub_port }}:8000"
    mounts:
      - type: bind
        src: /var/run/docker.sock
        dst: /var/run/docker.sock
      - type: volume
        src: jupyterhub-storage
        dst: /data
    haproxy:
      jupyterhub:
        enabled: "{{ enable_jupyterhub }}"
        mode: "http"
        port: "{{ jupyterhub_port }}"
        listen_port: "{{ jupyterhub_port }}"
      jupyterhub_external:
        enabled: "{{ enable_jupyterhub_external }}"
        frontend_enabled: "{{ enable_jupyterhub_external_frontend }}"
        mode: "http"
        external: true
        port: "{{ jupyterhub_port }}"
        listen_port: "{{ jupyterhub_port }}"
  jupyterhub_db:
    group: jupyterhub
    enabled: true
    image: mariadb:10.3
    network: "{{ jupyterhub_docker_network }}"
    environment:
      MYSQL_ROOT_PASSWORD: "{{ jupyterhub_db_root_password }}"
      MYSQL_USER: "{{ jupyterhub_db_user }}"
      MYSQL_PASSWORD: "{{ jupyterhub_db_password }}"
      MYSQL_DATABASE: "{{ jupyterhub_db_db }}"
    mounts:
      - type: volume
        src: jupyterhub-db-storage
        dst: /var/lib/mysql

jupyterhub_enable_ceph: no
jupyterhub_ceph_cluster: ceph
jupyterhub_ceph_client: client.jupyter
jupyterhub_ceph_pool: jupyter-volumes
jupyterhub_ceph_docker_volume_driver: docker.chameleoncloud.org/wetopi/rbd:latest
jupyterhub_ceph_docker_volume_driver_alias: rbd

jupyterhub_notebook_tag: 7f3a5e5
jupyterhub_notebook_image_full: "docker.chameleoncloud.org/jupyterhub-user:{{ jupyterhub_notebook_tag }}"
jupyterhub_notebook_workdir: /work

jupyterhub_keycloak_client_id: jupyterhub-prod
jupyterhub_keycloak_client_secret:

jupyterhub_artifact_sharing_keystone_user: trovi
jupyterhub_artifact_sharing_keystone_trust_project_name:
jupyterhub_artifact_sharing_swift_container:

jupyterhub_ks_services: []
jupyterhub_ks_users:
  - project: service
    user: "{{ jupyterhub_artifact_sharing_keystone_user }}"
    password: "{{ jupyterhub_artifact_sharing_keystone_password }}"
    role: admin
  - project: "{{ jupyterhub_artifact_sharing_keystone_trust_project_name }}"
    user: "{{ jupyterhub_artifact_sharing_keystone_user }}"
    password: "{{ jupyterhub_artifact_sharing_keystone_password }}"
    role: member
