---
jupyterhub_config_path: /etc/jupyterhub
jupyterhub_crypt_key: ''
jupyterhub_docker_image: docker.chameleoncloud.org/jupyterhub:7f3cb61
jupyterhub_docker_network: jupyterhub
jupyterhub_docker_volume_name: jupyterhub-storage
jupyterhub_hostname: jupyter.chameleoncloud.org
jupyterhub_port: 8000
jupyterhub_service_name: jupyterhub
jupyterhub_user: jupyterhub

jupyterhub_db_service_name: jupyterhub-db
jupyterhub_db_docker_image: mariadb:10.2
jupyterhub_db_docker_volume_name: jupyterhub-db-storage
jupyterhub_db_root_password: ''
jupyterhub_db_user: jupyterhub
jupyterhub_db_password: ''
jupyterhub_db_db: jupyterhub

jupyterhub_notebook_docker_image: docker.chameleoncloud.org/jupyterhub-user:c6deec5
jupyterhub_notebook_workdir: /work
