---
jupyterhub_config_path: /etc/jupyterhub
jupyterhub_crypt_key: ''
jupyterhub_docker_image: docker.chameleoncloud.org/jupyterhub:414997d
jupyterhub_docker_network: jupyterhub
jupyterhub_docker_network_subnet: 172.18.20.0/24
jupyterhub_docker_volume_name: jupyterhub-storage
jupyterhub_hostname: jupyter.chameleoncloud.org
jupyterhub_port: 8075 # Just needs to be something that doesn't conflict
jupyterhub_service_name: jupyterhub
jupyterhub_user: jupyterhub

jupyterhub_db_service_name: jupyterhub-db
jupyterhub_db_docker_image: mariadb:10.2
jupyterhub_db_docker_volume_name: jupyterhub-db-storage
jupyterhub_db_root_password: ''
jupyterhub_db_user: jupyterhub
jupyterhub_db_password: ''
jupyterhub_db_db: jupyterhub

jupyterhub_notebook_docker_image: docker.chameleoncloud.org/jupyterhub-user:4d56bd0
jupyterhub_notebook_workdir: /work
