---
chameleon_usage_docker_image: docker.chameleoncloud.org/chameleon_usage:latest
chameleon_usage_config_dir: /etc/chameleon_usage
chameleon_usage_mysql_user: cc_usage
chameleon_portal_mysql_host: udcc-db01.tacc.utexas.edu
chameleon_portal_mysql_user: chameleon_ro
ga_reporting_private_key_json_location: /root/ga-service-account-private-key.json
google_analytics_view_id: 90514617

usage_report_cron_name: usage_report
usage_report_cron_minute: '0'
usage_report_cron_hour: '3'
usage_report_cron_day: '*'
usage_report_cron_month: '*'
usage_report_cron_weekday: '*'
usage_report_cron_script: /usr/local/sbin/usage.py
usage_report_credentials: /usr/local/sbin/usage-credentials
cron_notification: /usr/local/sbin/notification

usage_report_tas_url: 'https://tas.tacc.utexas.edu/api'
usage_report_tas_usr: 'tasclient'
usage_report_mysql_tacc: '10.20.111.249'
usage_report_mysql_uc: '192.5.87.4'
usage_report_mysql_kvm: '10.20.111.245'
usage_report_mysql_user: 'usage'
usage_report_portal_host: 'udcc-db01.tacc.utexas.edu'
usage_report_portal_user: 'chameleon_ro'

