---
ironic_provisioning_network_cidr: 10.51.0.0/24
ironic_provisioning_network_gateway: "{{ ironic_provisioning_network_cidr | next_nth_usable(1) }}"
ironic_provisioning_allocation_pool_start: "{{ ironic_provisioning_network_cidr | next_nth_usable(2) }}"
ironic_provisioning_allocation_pool_end: "{{ ironic_provisioning_network_cidr | ipaddr('last_usable') }}"
ironic_dnsmasq_dhcp_range: "{{ ironic_provisioning_allocation_pool_start }},{{ ironic_provisioning_allocation_pool_end }}"

ironic_gateway_interface: "{{ network_interface | replace('_', '-') }}.{{ ironic_provisioning_network_vlan }}"
manage_ironic_gateway_interface: false

ironic_glance_images:
  - name: pxe_deploy_kernel_tinyipa
    container_format: aki
    disk_format: aki
    url: "https://tarballs.opendev.org/openstack/ironic-python-agent/tinyipa/files/tinyipa-stable-{{ openstack_release }}.vmlinuz"
  - name: pxe_deploy_ramdisk_tinyipa
    container_format: aki
    disk_format: aki
    url: "https://tarballs.opendev.org/openstack/ironic-python-agent/tinyipa/files/tinyipa-stable-{{ openstack_release }}.gz"
  - name: pxe_deploy_kernel
    container_format: aki
    disk_format: aki
    url: "https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ipa-centos8-stable-{{ openstack_release }}.kernel"
  - name: pxe_deploy_ramdisk
    container_format: aki
    disk_format: aki
    url: "https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ipa-centos8-stable-{{ openstack_release }}.initramfs"
  - name: cirros-0.6.2
    container_format: bare
    disk_format: qcow2
    url: "http://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img"
