---
- name: Configure chameleon image deployer docker bash wrapper
  become: yes
  template:
    src: chameleon-image-deploy.j2
    mode: 0700
    dest: /usr/local/sbin/chameleon-image-deploy

- name: Set up image deployer periodic task
  include_role:
    name: chameleon.periodic_task
    apply:
      become: yes
  vars:
    task_name: "image_deploy"
    task_command: "/usr/local/sbin/chameleon-image-deploy"
    task_calendar: "daily"
