---
- name: Pull Docker image
  become: True
  docker_image:
    source: pull
    name: "{{ chameleon_image_tools_docker_image }}"
    force_source: yes

- name: Cleanup old image deployer artifacts
  import_tasks: image_deployer_cleanup.yml
  when: enable_image_deployer | bool

# Setup new chameleon-image-deploy
- name: Create config directory
  become: yes
  file:
    path: "{{ chameleon_image_tools_config_dir }}"
    state: directory

- name: Configure site.yaml
  become: yes
  template:
    src: site.yaml.j2
    dest: "{{ chameleon_image_tools_config_dir }}/site.yaml"
    mode: '0600'
    owner: 'root'
    group: 'root'

- name: template envvars file
  become: yes
  template:
    src: envvars.j2
    dest: "{{ chameleon_image_tools_config_dir }}/envvars"
    mode: '0600'
    owner: 'root'
    group: 'root'

- name: Deploy chameleon-image-deploy systemd service
  become: yes
  template:
    src: chameleon-image-deploy.service.j2
    dest: /etc/systemd/system/{{ chameleon_site_name }}-chameleon-image-deploy.service
    mode: '0644'
  when: enable_image_deployer | bool

- name: Deploy chameleon-image-deploy timer unit
  become: yes
  template:
    src: chameleon-image-deploy.timer.j2
    dest: /etc/systemd/system/chameleon-image-deploy.timer
    mode: '0644'
  when: enable_image_deployer | bool

- name: Reload systemd to pick up new/changed units
  become: yes
  systemd:
    daemon_reload: yes
  when: enable_image_deployer | bool

- name: Enable & start chameleon-image-deploy.timer
  become: yes
  systemd:
    name: chameleon-image-deploy.timer
    enabled: yes
    state: started
  when: enable_image_deployer | bool
