[filter_scheduler]
available_filters = nova.scheduler.filters.all_filters
available_filters = blazarnova.scheduler.filters.blazar_filter.BlazarFilter
enabled_filters = ComputeFilter, ComputeCapabilitiesFilter, ImagePropertiesFilter, ServerGroupAntiAffinityFilter, ServerGroupAffinityFilter, PciPassthroughFilter, BlazarFilter

[pci]

report_in_placement = True

{% if nova_pci_device_spec is defined %}
device_spec = {{ nova_pci_device_spec | to_json }}
{% endif %}

{% for alias in nova_pci_alias | default('[]') %}
alias = {{ alias | to_json }}
{% endfor %}

{% if service_name == "nova-api" %}
# Custom vendordata service
[api]
vendordata_providers = DynamicJSON
vendordata_dynamic_targets = chameleon@http://127.0.0.1:8911
vendordata_dynamic_read_timeout = "{{ vendordata_read_timeout:-5 }}"

[vendordata_dynamic_auth]
auth_type = password
auth_url = {{ keystone_internal_url }}
project_name = service
project_domain_id = default
username = {{ nova_keystone_user }}
user_domain_id = default
password = {{ nova_keystone_password }}

{% endif %}
