[filter_scheduler]
available_filters = nova.scheduler.filters.all_filters
enabled_filters = ComputeFilter, ComputeCapabilitiesFilter, ImagePropertiesFilter, ServerGroupAntiAffinityFilter, ServerGroupAffinityFilter, PciPassthroughFilter

[pci]

report_in_placement = True

device_spec = {{ nova_pci_device_spec | to_json }}

{% for alias in nova_pci_alias %}
alias = {{ alias | to_json }}
{% endfor %}
