---
hammers_config_path: /etc/hammers
hammers_docker_image: docker.chameleoncloud.org/hammers:latest
hammers_env_file: /etc/hammers/hammers.env
hammers_mysql_user: cc_hammers

hammers:
  neutron_reaper_ip:
    hammer_name: hammers-neutronreaper-ip
    cmd: neutron-reaper
    extra_args:
      - delete
      - ip
      - 14
    cron_times:
      minute: 20
      hour: 5
  conflict_macs:
    hammer_name: hammers-conflictmacs
    cmd: conflict-macs
    extra_args:
      - delete
    cron_times:
      minute: 30
      hour: 5
  undead_instances:
    hammer_name: hammers-undeadinstances
    cmd: undead-instances
    extra_args:
      - delete
    cron_times:
      minute: 35
      hour: 5
  dirty_ports:
    hammer_name: hammers-dirtyports
    cmd: diryt-ports
    extra_args:
      - clean
      - --multiport
    cron_times:
      minute: 15
  ironic_error_resetter:
    hammer_name: hammers-ironicerrorresetter
    cmd: ironic-error-resetter
    extra_args:
      - reset
    cron_times:
      minute: "*/15"
  orphan_resource_providers:
    hammer_name: hammers-orphanresourceproviders
    cmd: orphan-resource-providers
    extra_args:
     - update
    cron_times:
      minute: 45
      hour: 5
  reservation_usage_notification:
    hammer_name: hammers-reservationusagenotfication
    cmd: reservation-usage-notification
    cron_times:
      minute: 0
      hour: 10
  orphans_detector:
    hammer_name: hammers-orphansdetector
    cmd: orphans-detector
    cron_times:
      minute: 45
      hour: 5
