---
hammers_config_path: /etc/hammers
hammers_docker_image: "{{ docker_registry }}/hammers:latest"
hammers_env_file: /etc/hammers/hammers.env
hammers_mysql_user: cc_hammers
hammers_mysql_host: "{{ database_address }}"

hammers:
  floating_ip_reaper:
    cmd: floatingip-reaper --grace-days 7
    calendar: daily
  conflict_macs:
    cmd: conflict-macs delete
    calendar: daily
  undead_instances:
    cmd: undead-instances delete
    calendar: daily
  dirty_ports:
    cmd: dirty-ports clean --multiport
    calendar: daily
  ironic_error_resetter:
    cmd: ironic-error-resetter reset
    calendar: hourly
  orphan_resource_providers:
    cmd: orphan-resource-providers update
    calendar: daily
  reservation_usage_notification:
    cmd: "reservation-usage-notification"
    calendar: daily
  orphans_detector:
    cmd: "orphans-detector"
    calendar: daily
  lease_stacking:
    cmd: "lease-stack-reaper delete"
    calendar: daily
  clean_old_aggregates:
    cmd: "clean-old-aggregates"
    calendar: daily
  unutilized_leases:
    cmd: "unutilized-lease-reaper delete"
    calendar: hourly
  enforce_node_retirement:
    cmd: "retirement-enforcer"
    calendar: daily
