---
hammers_config_path: /etc/hammers
hammers_docker_image: "{{ docker_registry }}/hammers:latest"
hammers_env_file: /etc/hammers/hammers.env
hammers_mysql_user: cc_hammers
hammers_mysql_host: "{{ database_address }}"
hammers_lease_stacking_notification_email: help@chameleoncloud.org
hammers_lease_stacking_excluded_projects:
 - chameleon
 - openstack

hammers:
  # Networking/Neutron
  floating_ip_reaper:
    cmd: floatingip-reaper --grace-days 7
    calendar: daily
    enabled: "{{ enable_neutron | bool }}"
  conflict_macs:
    cmd: conflict-macs delete
    calendar: daily
    enabled: "{{ enable_neutron | bool }}"

  # Compute/Nova
  undead_instances:
    cmd: undead-instances delete
    calendar: daily
    enabled: "{{ enable_nova | bool }}"

  # Bare metal/Ironic
  dirty_ports:
    cmd: dirty-ports clean --multiport
    calendar: daily
    enabled: "{{ enable_ironic | bool }}"
  ironic_error_resetter:
    cmd: ironic-error-resetter reset
    calendar: hourly
    enabled: "{{ enable_ironic | bool }}"
  enforce_node_retirement:
    cmd: "retirement-enforcer"
    calendar: daily
    enabled: "{{ enable_ironic | bool }}"

  # Reservation/Blazar
  orphan_resource_providers:
    cmd: orphan-resource-providers update
    calendar: daily
    enabled: "{{ enable_blazar | bool }}"
  reservation_usage_notification:
    cmd: "reservation-usage-notification"
    calendar: daily
    enabled: "{{ enable_blazar | bool }}"
  orphans_detector:
    cmd: "orphans-detector"
    calendar: daily
    enabled: "{{ enable_blazar | bool }}"
  lease_stacking:
    cmd: "lease-stack-notifier {{ hammers_lease_stacking_action }} {{ openstack_region_name}} --exclude_projects {% for project in hammers_lease_stacking_excluded_projects %}{{ project }} {% endfor %} --manager_email hammers_lease_stacking_notification_email"
    calendar: daily
    enabled: "{{ enable_blazar | bool }}"
  clean_old_aggregates:
    cmd: "clean-old-aggregates"
    calendar: daily
    enabled: "{{ enable_blazar | bool }}"
  unutilized_leases:
    cmd: "unutilized-lease-reaper delete"
    calendar: hourly
    enabled: "{{ enable_blazar | bool }}"

hammers_slack_webhook: "{{ slack_api_url }}"
