groups:
- name: baremetal
  rules:
  - alert: NovaIronicInstanceLaunchFailure
    expr: sum(increase(launch_failure[1h])) by (hostname) > 3
    labels:
      severity: warning
      can_resolve: no
    annotations:
      summary: "Instance launches are failing"
      description: "A significant number of instance launches on {{ $labels.hostname }} have failed in the past hour."

  - alert: IronicNodeInErrorState
    expr: sum(openstack_node_totals{provision_state="error",maintenance="False"}) by (hostname, name)
    labels:
      severity: critical
      can_resolve: no
    annotations:
      summary: "Ironic node in error provision state"
      description: "Ironic node {{ $labels.name }} on {{ $labels.hostname }} is in an error provision state."
