groups:
- name: baremetal
  rules:
  - alert: NovaIronicInstanceLaunchFailure
    expr: sum(increase(launch_failure[1h])) by (hostname) > 3
    labels:
      severity: warning
      can_resolve: no
    annotations:
      summary: "Instance launches are failing"
      description: "A significant number of instance launches on {{ $labels.hostname }} have failed in the past hour."
