groups:
- name: control_node
  rules:

  - alert: IronicLowImageCacheSpace
    expr: |
      min(node_filesystem_avail_bytes{mountpoint=~"/var(/lib(/(docker|ironic))?)?"})
      by (hostname)
      <
      (1024 * 1024 * 1024 * 15)
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Low Ironic cache space on {{ $labels.hostname }}"
      description: "Ironic process on {{ $labels.hostname }} has less than 15GB of space to use for image cache."
