groups:
- name: control_node
  rules:

  - alert: IronicLowImageCacheSpace
    expr: |
      min(node_filesystem_avail_bytes{mountpoint=~"/var(/lib(/(docker|ironic))?)?"})
      by (hostname)
      <
      (1024 * 1024 * 1024 * 15)
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Low Ironic cache space on {{ $labels.hostname }}"
      description: "Ironic process on {{ $labels.hostname }} has less than 15GB of space to use for image cache."

  - alert: NodeExporterDown
    expr: up == 0
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "Exporter job *{{ $labels.job }}* is down"
      description: "The exporter job *{{ $labels.job }}* on {{ $labels.hostname }} is no longer returning metrics."

  - alert: NodeNetworkBridgeDown
    expr: |
      max_over_time(node_network_transmit_packets_total{device=~"br.*"}[1h])
      unless node_network_transmit_packets_total
    labels:
      severity: critical
    annotations:
      summary: "Bridge *{{ $labels.device }}* is no longer reporting metrics"
      description: "The network bridge *{{ $labels.device }}* on {{ $labels.hostname }} could be down."

  - alert: NodeNetworkBridgeLowTraffic
    expr: |
      rate(node_network_transmit_packets_total{device=~"br.*"}[5m])
        == 0
      and
      rate(node_network_transmit_packets_total{device=~"br.*"}[5m] offset 1d)
        > 0
    for: 30m
    labels:
      severity: warning
    annotations:
      summary: "Bridge *{{ $labels.device }}* has lower than normal packet activity"
      description: "The network bridge *{{ $labels.device }}* on {{ $labels.hostname }} had no traffic for the last 30 minutes."

  - alert: OpenStackAPIDown
    expr: openstack_check_api == 0
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: "OpenStack {{ $labels.service | title }} service is down"
      description: "The *{{ $labels.service | title }}* service on {{ $labels.hostname }} is not responding."
      runbook: https://github.com/ChameleonCloud/chi-in-a-box/wiki/%5BRunbook%5D-OpenStackAPIDown
