---
- set_fact:
    prometheus_docker_network_ipv4: "{{ prometheus_docker_network_subnet | ipv4('net') }}"

- name: Create MySQL user.
  local_action:
    module: mysql_user
    login_host: "{{ groups.mariadb[0] }}"
    login_password: "{{ database_password }}"
    name: "{{ prometheus_mysql_exporter_user }}"
    host: "{{ prometheus_docker_network_ipv4 | ipaddr('network') }}/{{ prometheus_docker_network_ipv4 | ipaddr('netmask') }}"
    password: "{{ prometheus_mysql_exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
  vars:
    # Ensure when we run this on the ansible host, we use the Virtualenv
    # (which should already be set up.)
    ansible_python_interpreter: "{{ ansible_python_interpreter }}"

- name: Configure MySQL exporter.
  template:
    src: mysql_exporter.my.cnf.j2
    dest: "{{ service.config_dir }}/my.cnf"
  vars:
    mysql_host: "{{ ansible_internal_ipv4_addresses[groups.mariadb[0]] }}"
  notify:
    - restart mysql exporter
