---
- name: Create node_exporter user.
  user:
    name: node_exporter
    system: True
    shell: /sbin/nologin
    create_home: False
    comment: Prometheus Node Exporter
  become: yes
  become_user: root

# TODO: this could really be better. We could download different versions side
# by side and symlink the latest, which would probably help ansible figure out
# when it actually needed to do work.
- name: "Install node_exporter to {{ service.bin_path }}"
  block:
    - name: Download node_exporter binary tarball.
      get_url:
        url: "{{ service.bin_url }}"
        dest: "/tmp/node_exporter.tar.gz"
    - name: Unarchive node_exporter binary tarball.
      unarchive:
        copy: no
        src: "/tmp/node_exporter.tar.gz"
        dest: "{{ service.bin_path }}"
        extra_opts:
          - --strip-components=1
        creates: "{{ service.bin_path }}/node_exporter"
      become: yes
      become_user: root
      notify:
        - restart node exporter

# I'm not sure this is even necessary. Node exporter could run without sudo perhaps.
- name: Allow user to run node_exporter.
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^node_exporter"
    line: "node_exporter localhost={{ service.bin_path }}/node_exporter"
    validate: "visudo -cf %s"
  become: yes
  become_user: root
