---
- template:
    src: prometheus.yml.j2
    dest: "{{ service.config_dir }}/prometheus.yml"

- copy:
    src: "{{ item }}"
    dest: "{{ service.config_dir }}/{{ item }}"
  loop:
    - control-rules.yml
    - mysql-rules.yml
