---
- template:
    src: prometheus.yml.j2
    dest: "{{ service.config_dir }}/prometheus.yml"
  notify:
    - restart prometheus

- copy:
    src: "rules"
    dest: "{{ service.config_dir }}"
  notify:
    - restart prometheus
