---
- template:
    src: prometheus.yml.j2
    dest: "{{ service.config_dir }}/prometheus.yml"
  notify:
    - restart prometheus

- file:
    name: "{{ service.config_dir }}/secrets"
    state: directory
    # Prometheus server container runs as user=nobody
    owner: nobody
    mode: 0640

- file:
    name: "{{ service.config_dir }}/rules"
    state: directory

- copy:
    src: "{{ item }}"
    dest: "{{ service.config_dir }}/rules/{{ item }}"
  loop:
    - baremetal-rules.yml
    - control-rules.yml
    - mysql-rules.yml
  notify:
    - restart prometheus
