---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ chameleon_swift_auth }}"
    service_ks_register_services: "{{ chameleon_swift_ks_services }}"
    service_ks_register_users: "{{ chameleon_swift_ks_users }}"
  tags: always
