---
- name: Create Admin-Only VM flavors
  kolla_toolbox:
    module_name: os_nova_flavor
    module_args:
      auth: "{{ openstack_auth }}"
      state: present
      name: admin-small
      interface: admin
      is_public: no
      disk: 20
      ram: 8
      vcpus: 4
  run_once: True
  when: enable_nova | bool
