---
- name: Create KVM flavors
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: openstack.cloud.compute_flavor
    module_args:
      auth: "{{ openstack_auth }}"
      state: present
      name: "{{ item.name }}"
      is_public: "{{ item.is_public }}"
      disk: "{{ item.disk_gb }}"
      ram: "{{ item.ram_mb }}"
      vcpus: "{{ item.vcpus }}"
  run_once: True
  when:
    - enable_nova | bool
    - chameleon_enable_virtual | bool
