grafana_docker_image: grafana/grafana:5.2.2
grafana_docker_volume_name: grafana-data

grafana_hostname: grafana.chameleon.tacc.utexas.edu
grafana_port: 3000
grafana_config_path: /etc/grafana

grafana_auth_ldap_hostname: ldap.tacc.utexas.edu
grafana_auth_ldap_port: 389
grafana_auth_ldap_user_treebase: ou=People,dc=tacc,dc=utexas,dc=edu
grafana_auth_ldap_user_search_filter: (uid=%s)
grafana_auth_ldap_group_treebase: ou=Chameleon,ou=Systems,dc=tacc,dc=utexas,dc=edu
grafana_auth_ldap_group_search_filter: (&(objectClass=groupOfNames)(member=uid=%s,ou=People,dc=tacc,dc=utexas,dc=edu))
grafana_auth_ldap_editor_group: Chameleon
