---
- name: Pull Docker image.
  docker_image:
    source: pull
    name: "{{ redfish_monitor_docker_image }}"
    force_source: yes

- name: Create config directory.
  file:
    path: "{{ redfish_monitor_config_path }}"
    state: directory

- name: Create log directory.
  file:
    path: "{{ redfish_monitor_log_folder }}"
    state: directory

- name: Configure redfish-monitor env file
  template:
    src: redfish-monitor.env.j2
    mode: 0600
    dest: "{{ redfish_monitor_env_file }}"

- name: Create redfish_monitor services.
  template:
    src: "redfish_monitor.service.j2"
    dest: "/usr/lib/systemd/system/redfish_monitor.service"
  notify:
    - reload systemd daemon
    - restart redfish monitor

- name: Enable redfish_monitor service.
  systemd:
    service: redfish_monitor
    state: started
    enabled: yes
