---
chameleon_reference_repo_docker_image: "{{ chameleon_site_tools_image_full }}"
chameleon_reference_repo_config_dir: /etc/hammers

chameleon_reference_repo_url: https://github.com/ChameleonCloud/reference-repository.git
chameleon_reference_repo_push_changes: true
