---
backup_database_user: backup

deployment_dir: "{{ deployment_dir }}"
deployment_site_config_dir: "{{ site_config_dir }}"
mariadb_backup_timer_suffix: "{{ site_config_dir | basename }}"
mariadb_backup_cron_script: /usr/local/sbin/mariadb-backup
mariadb_backup_max_packet: 1M
mariadb_backup_file_age: 29
mariadb_backup_file: mariadb-backup
mariadb_backup_retention: +31
mariadb_backup_s3_conf_dir: /etc/awsconf
mariadb_backup_log_key: chameleon-chi-db-backup

mariadb_backup_s3_key_id:
mariadb_backup_s3_endpoint:
mariadb_backup_container_name: backup
