---
backup_database_user: backup

deployment_dir: "{{ deployment_dir }}"
deployment_site_config_dir: "{{ site_config_dir }}"
mariadb_backup_timer_suffix: "{{ site_config_dir | basename }}"
mariadb_backup_cron_script: /usr/local/sbin/mariadb-backup
mariadb_backup_file_age: 29
mariadb_backup_s3_endpoint:
mariadb_backup_s3_key_id:
mariadb_backup_s3_key:
# if mariadb_backup_container_name is defined, use that
mariadb_backup_bucket_name: "{{ mariadb_backup_container_name | default() }}"

# these parameters are copied from kolla-ansible/ansible/roles/common/defaults/main.yml
# because this playbook is executed outside the context of that role
kolla_toolbox_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/kolla-toolbox"
kolla_toolbox_tag: "{{ openstack_tag }}"
kolla_toolbox_image_full: "{{ kolla_toolbox_image }}:{{ kolla_toolbox_tag }}"

rclone_image: "rclone/rclone:1.67"