---
backup_database_user: backup

deployment_dir: "{{ deployment_dir }}"
deployment_site_config_dir: "{{ site_config_dir }}"
mariadb_backup_timer_suffix: "{{ site_config_dir | basename }}"
mariadb_backup_cron_script: /usr/local/sbin/mariadb-backup
mariadb_backup_max_packet: 1M
mariadb_backup_file_age: 29
mariadb_backup_s3_conf_dir: /etc/awsconf
mariadb_backup_container_name: backup

kolla_toolbox_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-kolla-toolbox"
kolla_toolbox_tag: "{{ openstack_release }}"
kolla_toolbox_image_full: "{{ kolla_toolbox_image }}:{{ kolla_toolbox_tag }}"
