prometheus_docker_network_name: prometheus
prometheus_docker_network_subnet: 172.18.0.0/24

# Users allowed to access the web UIs
prometheus_users: []

prometheus_monitoring_user: monitoring
prometheus_server_users: "{{ prometheus_users }}"

enable_prometheus_alertmanager: yes
# This should be encrypted! It is a secret value.
prometheus_alertmanager_slack_api_url: "{{ slack_api_url }}"
prometheus_alertmanager_users: "{{ prometheus_users }}"

prometheus_mysql_exporter_user: mysqld-exporter

prometheus_openstack_exporter_user: admin

prometheus_services:
  server:
    service_name: prometheus_server
    image: prom/prometheus:v2.10.0
    group: prometheus
    enabled: yes
    restart_handler: restart prometheus
    port: 9090
    config_dir: /etc/prometheus
    scrape_target: yes
    service_args:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.external-url=https://{{ prometheus_server_hostname }}:9090"
    volumes:
      - "prometheus-data:/prometheus"
      - "/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/etc/prometheus/rules:/etc/prometheus/rules"
      - "/etc/prometheus/secrets:/etc/prometheus/secrets"
  alertmanager:
    service_name: prometheus_alertmanager
    image: prom/alertmanager:v0.15.2
    group: prometheus-alertmanager
    enabled: yes
    restart_handler: restart alertmanager
    port: 9093
    config_dir: /etc/alertmanager
    service_args:
      - "--web.external-url=https://{{ prometheus_alertmanager_hostname }}"
    scrape_target: no
    volumes:
      - "alertmanager-data:/alertmanager"
      - "/etc/alertmanager:/etc/alertmanager"
  jupyterhub-exporter:
    group: jupyterhub
    port: 8075
    scrape_target: yes
    enabled: "{{ enable_jupyterhub }}"
    bearer_token_file: /etc/prometheus/secrets/jupyterhub
  mysql-exporter:
    service_name: prometheus_mysql_exporter
    image: prom/mysqld-exporter:v0.11.0
    group: prometheus-mysqld-exporter
    enabled: yes
    restart_handler: restart mysql exporter
    port: 9104
    config_dir: /etc/prometheus/mysqld-exporter
    scrape_target: yes
    volumes:
      - "/etc/prometheus/mysqld-exporter/my.cnf:/root/.my.cnf"
  node-exporter:
    service_name: prometheus_node_exporter
    group: prometheus-node-exporter
    enabled: yes
    restart_handler: restart node exporter
    custom_service: yes
    port: 9100
    bin_path: /usr/sbin
    bin_url: https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
    scrape_target: yes
  openstack-exporter:
    service_name: prometheus_openstack_exporter
    image: docker.chameleoncloud.org/chameleoncloud/prometheus-openstack-exporter:latest
    group: prometheus-openstack-exporter
    enabled: yes
    restart_handler: restart openstack exporter
    port: 9103
    config_dir: /etc/prometheus
    env_file: /etc/prometheus/openstack_exporter.env
    scrape_target: yes
    volumes:
      - "/etc/prometheus/openstack_exporter.yml:/usr/local/bin/exporter/config.yml"
  redis-exporter:
    service_name: prometheus_redis_exporter
    image: oliver006/redis_exporter:latest
    group: prometheus-redis-exporter
    enabled: yes
    restart_handler: restart redis exporter
    port: 9121
    scrape_target: yes
    service_args:
      # TODO(jason): this is a complete hack and means this configuration is
      # ONLY valid for the allocations DB. But, it's currently the only place
      # we use Redis.
      - "--redis.addr=redis://allocations_db:6379"
  snmp-exporter:
    service_name: prometheus_snmp_exporter
    image: prom/snmp-exporter:v0.15.0
    generator_image: prom/snmp-generator:master
    group: prometheus-snmp-exporter
    enabled: yes
    restart_handler: restart snmp exporter
    port: 9116
    config_dir: /etc/prometheus/snmp-exporter
    scrape_target: no
    volumes:
     - "/etc/prometheus/snmp-exporter:/etc/snmp_exporter"
  # The Ceph exporters use the built-in Prometheus metrics agent Ceph provides
  ceph-exporter:
    group: prometheus-ceph-exporter
    enabled: yes
    port: 9283
    scrape_target: yes
  push-gateway:
    service_name: prometheus_pushgateway
    image: prom/pushgateway:v0.8.0
    group: prometheus-push-gateway
    enabled: yes
    restart_handler: restart pushgateway
    port: 9091
    config_dir: /etc/prometheus
    scrape_target: yes
  precis-event-listener-exporter:
    group: precis
    enabled: "{{ enable_precis }}"
    port: 8913
    scrape_target: yes
  precis-endpoint-exporter:
    group: precis
    enabled: "{{ enable_precis }}"
    port: 8912
    scrape_target: yes
  allocations-exporter:
    group: allocations
    enabled: "{{ enable_allocations }}"
    port: 8916
    scrape_target: yes
