---
- hosts: deployment
  roles:
    - role: chameleon_mariadb
      when: enable_mariabackup | bool
      vars:
          action: 'deployment'

- hosts: mariadb
  roles:
    - role: chameleon_mariadb
      vars:
          action: 'config'
  tags: [ mariadb, all ]
