---
- hosts: mariadb
  roles:
    - mariadb
  tags: [ mariadb, all ]

- hosts: backups-glance
  roles:
    - glance
  tags: [ glance, all ]

- hosts: gnocchi
  roles:
    - gnocchi
  tags: [ gnocchi, all ]
