---
- hosts: chameleon_usage
  roles:
    - role: chameleon_usage
      vars:
          action: 'mysql_init'
    - role: chameleon_usage
      vars:
          action: 'config'
    - role: chameleon_usage
      vars:
          action: 'node'
    - role: chameleon_usage
      when: enable_usage_appliance_report
      vars:
          action: 'heat_template'
    - role: chameleon_usage
      when: enable_usage_report_sync
      vars:
          action: 'usage_report'

- hosts: chameleon_usage_jupyter
  roles:
    - role: chameleon_usage
      vars:
          action: 'config'
    - role: chameleon_usage
      vars:
          action: 'jupyter'
