---
- hosts: chameleon_usage
  roles:
    - role: chameleon_usage
      vars:
          action: 'mysql_init'
    - role: chameleon_usage
      vars:
          action: 'config'
    - role: chameleon_usage
      vars:
          action: 'node'
    - role: chameleon_usage
      when: enable_usage_appliance_report | bool
      vars:
          action: 'heat_template'
    - role: chameleon_usage
      when: enable_user_project_report | bool
      vars:
          action: 'user_project'

- hosts: chameleon_usage_jupyter
  roles:
    - role: chameleon_usage
      vars:
          action: 'config'
    - role: chameleon_usage
      when: enable_jupyter_report | bool
      vars:
          action: 'jupyter'
