---
- hosts: baremetal
  tasks:
    - name: Add common cron jobs
      include_role:
        name: chameleon_common
        defaults_from: cron
        tasks_from: cron
    - name: Add fluentd restart job
      cron:
        name: "{{ job_name }}"
        minute: 0
        hour: "*/6"
        job: "/usr/bin/docker restart fluentd | /usr/bin/logger -t {{ job_name }} && {{ cron_notification }} {{ job_name }}"
      vars:
        job_name: restart-fluentd

- hosts: elasticsearch
  tasks:
    - name: Add ElasticSearch cron job
      include_role:
        name: chameleon_common
        tasks_from: elasticsearch
