---
- hosts: docker_registry
  roles:
    - docker_registry
  tasks:
    - name: Set facts for gathering in frontend hosts.
      set_fact:
        docker_registry_hostname: "{{ docker_registry_hostname }}"
        docker_registry_port: "{{ docker_registry_port }}"
      tags:
        - configuration

- hosts: frontends
  tasks:
    - name: Configure virtual host for docker registry backend.
      block:
        - name: Gather facts from docker registry host.
          setup:
          delegate_to: "{{ groups.docker_registry[0] }}"
          delegate_facts: True
        - name: Precompute convenience facts needed for virtual host configuration.
          set_fact:
            docker_registry_hostname: "{{ hostvars[groups.docker_registry[0]].docker_registry_hostname }}"
            docker_registry_port: "{{ hostvars[groups.docker_registry[0]].docker_registry_port }}"
            docker_registry_auth_allow_push_projects: "{{ hostvars[groups.docker_registry[0]].docker_registry_auth_allow_push_projects }}"
            docker_registry_internal_address: "{{ groups.docker_registry[0] }}"
        - name: Configure virtual host.
          include_role:
            name: apache
            tasks_from: host
          vars:
            apache_server_name: "{{ docker_registry_hostname }}"
            apache_server_conf: |
              ProxyPass        /v2 http://{{ docker_registry_internal_address }}:{{ docker_registry_port }}/v2
              ProxyPassReverse /v2 http://{{ docker_registry_internal_address }}:{{ docker_registry_port }}/v2

              <Location /v2>
                Order deny,allow
                Allow from all

                AuthType Basic
                AuthName "Registry Authentication"
                AuthBasicProvider external
                AuthExternal keystone-user
                GroupExternal keystone-project

                # Read access to all authentified users
                Require valid-user

                # TODO: Write access to operators
                <Limit POST PUT DELETE PATCH>
                  # Require external-group {{ docker_registry_auth_allow_push_projects }}
                </Limit>
              </Location>
      tags:
        - configuration
