---
- hosts: jupyterhub
  roles:
    - name: jupyterhub
      when: enable_jupyterhub | bool

- hosts: haproxy
  tasks:
    - include_role:
        name: jupyterhub
        tasks_from: loadbalancer
      when:
        - enable_jupyterhub | bool
        - enable_haproxy | bool
