---
- hosts: keycloak
  roles:
    - name: keycloak
      when: enable_keycloak | bool

- hosts: haproxy
  tasks:
    - include_role:
        name: keycloak
        tasks_from: loadbalancer
      when:
        - enable_keycloak | bool
        - enable_haproxy | bool

- hosts: keycloak_tas_sync
  roles:
    - name: keycloak_tas_sync
      when: enable_keycloak_tas_sync | bool
