---
- hosts: control
  roles:
    - role: post_networking
    - role: post_ironic
      when: enable_ironic

- hosts: neutron-l3-agent
  tasks:
    - name: configure calico/neutron floating-IP bridge
      ansible.builtin.import_role:
        name: post_networking
        tasks_from: neutron_calico_connect.yml
      when:
        - enable_k3s | bool
        - public_network is defined
        - public_network is mapping
        - public_network.name is defined

- hosts: vendordata
  roles:
    - role: vendordata
      when: enable_vendordata | bool

- hosts: hammers
  roles: [hammers]

- hosts: chameleon-image-tools
  roles: [chameleon_image_tools]

- hosts: chameleon-periodic-inspector
  roles: [chameleon_periodic_inspector]

- hosts: chameleon-reference-repo
  roles: [chameleon_reference_repo]

- hosts: deployment
  roles:
    - role: chameleon_mariadb
      when: hostvars[groups['mariadb'][0]]['enable_mariabackup'] | bool
      vars:
        action: "deployment"
- hosts: mariadb
  roles:
    - role: chameleon_mariadb
      vars:
        action: "config"
  tags: mariadb

- hosts: chameleon_usage
  roles:
    - role: chameleon_usage
      when: enable_usage_reporting | bool

- name: Install and configure services for Precis
  hosts: precis
  roles: [precis]

- hosts: manila-nfs-ganesha
  roles:
    - role: filesystem
      when: enable_manila | bool
