---
- hosts: control
  roles:
    - role: post_networking
    - role: post_ironic
      when: enable_ironic

- hosts: vendordata
  roles: [vendordata]

- hosts: hammers
  roles: [hammers]

- hosts: chameleon-image-tools
  roles: [chameleon_image_tools]

- hosts: deployment
  roles:
    - role: chameleon_mariadb
      when: hostvars[groups['mariadb'][0]]['enable_mariabackup'] | bool
      vars:
        action: "deployment"
- hosts: mariadb
  roles:
    - role: chameleon_mariadb
      vars:
        action: "config"
  tags: mariadb

- hosts: chameleon_usage
  roles:
    - role: chameleon_usage
      when: enable_usage_reporting | bool

- name: Install and configure services for Precis
  hosts: precis
  roles: [precis]

- hosts: manila-nfs-ganesha
  roles:
    - role: filesystem
      when: enable_manila | bool
