---
- hosts: control
  roles:
    - role: post_networking
    - role: post_ironic
      when: enable_ironic
# Run other critical site playbooks

- hosts: vendordata
  roles:
    - vendordata
  become: yes
  become_user: root
  tags:
    - vendordata

- hosts: precis
  roles:
    - precis
  tags:
    - precis

- hosts: deployment
  roles:
    - role: chameleon_mariadb
      when: hostvars[groups['mariadb'][0]]['enable_mariabackup'] | bool
      vars:
        action: "deployment"

- hosts: mariadb
  roles:
    - role: chameleon_mariadb
      vars:
        action: "config"
  become: yes
  become_user: root
  tags:
    - mariadb

- hosts: mariadb
  roles:
    - role: chameleon_usage
      when: enable_usage_reporting | bool
  become: yes
  become_user: root

- hosts: hammers
  roles:
    - hammers
  become: yes
  become_user: root
  tags:
    - hammers

- hosts: chameleon-image-tools
  roles:
    - chameleon_image_tools
