---
- hosts: control
  roles:
    - role: post_networking
    - role: post_kvm
      when: enable_kvm
    - role: post_ironic
      when: enable_ironic

# Run other critical site playbooks
- name: Set up vendordata metadata for instances (critical)
  import_playbook: vendordata.yml

- name: Set up Hammers (periodic fix-it tasks)
  import_playbook: hammers.yml

- name: Set up Chameleon image download tools
  import_playbook: chameleon_image_tools.yml

- name: Set up mariadb automatic backups
  import_playbook: backups.yml

- name: Set up Chameleon usage reporting
  import_playbook: chameleon_usage.yml

- name: Set up Precis
  import_playbook: precis.yml
