---
- hosts: mysql

- hosts: rabbitmq

- hosts: precis
  roles:
    - precis
  tasks:
    - name: Configure virtual host.
      include_role:
        name: apache
        tasks_from: host
      vars:
        apache_server_bind_address: "{{ precis_vip_address }}"
        apache_server_priority: 25
        apache_server_alias: precis_public
        apache_server_name: "{{ precis_server_hostname }}"
        apache_ssl_letsencrypt_enabled: no
        apache_server_https_port: "{{ precis_endpoint_port }}"
        apache_server_http_port: null
        apache_server_ssl_certificate_file: "{{ precis_ssl_certificate_file }}"
        apache_server_ssl_certificate_key_file: "{{ precis_ssl_certificate_key_file }}"
        apache_server_ssl_ca_file: "{{ precis_ssl_ca_file }}"
        apache_server_conf: |
          ProxyPass        / http://{{ precis_internal_address }}:{{ precis_endpoint_port }}/
          ProxyPassReverse / http://{{ precis_internal_address }}:{{ precis_endpoint_port }}/
      when: precis_server_hostname is defined
