---
- hosts:
    - prometheus
    - prometheus-ceph-exporter
    - prometheus-jupyterhub-exporter
    - prometheus-mysqld-exporter
    - prometheus-node-exporter
    - prometheus-openstack-exporter
    - prometheus-push-gateway
    - prometheus-redis-exporter
  roles:
    - chameleon_prometheus
  tasks:
    - set_fact:
        prometheus_alertmanager_port: "{{ prometheus_services['prometheus-alertmanager'].port }}"
        prometheus_alertmanager_users: "{{ prometheus_alertmanager_users }}"
      when: inventory_hostname in groups[prometheus_services['prometheus-alertmanager'].group]
    - set_fact:
        prometheus_server_port: "{{ prometheus_services['prometheus-server'].port }}"
        prometheus_server_users: "{{ prometheus_server_users }}"
        prometheus_monitoring_user: "{{ prometheus_monitoring_user }}"
      when: inventory_hostname in groups[prometheus_services['prometheus-server'].group]
