---

- hosts: maintenance_nodes

  tasks:
  - name: install stress-ng and screen
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - stress-ng
        - screen

  - name: Register screen session
    find:
      paths: '/var/run/screen/S-root/'
      file_type: any
      patterns: '*.stress'
    register: screen_files

  - name: Fail if existing screen session
    fail:
      msg: A stress session is already running. It might be some pending writes to disk.
    when: screen_files.matched != 0

  - name: Stress CPU
    command: >
      screen -S stress -d -m
      stress-ng
      --timeout 1440m
      --vm-method all
      --vm 90%
      --vm-bytes 1G


  