---
- name: Ensure Nova configuration directory exists.
  file:
    name: "{{ node_custom_config }}/nova"
    state: directory

- name: Copy Nova configuration files.
  block:
    - copy:
        src: policy.json
        dest: "{{ node_custom_config }}/nova/policy.json"
    - template:
        src: "{{ item }}.j2"
        dest: "{{ node_custom_config }}/nova/{{ item }}"
      loop:
        - "nova-compute.conf"
