---
- name: Pull Docker Registry image.
  docker_image:
    name: "{{ docker_registry_image }}"
  tags:
    - pull

- name: Create OpenStack user for Swift storage.
  local_action:
    module: os_user
    name: "{{ docker_registry_swift_username }}"
    password: "{{ docker_registry_swift_password }}"
    region_name: "{{ keystone_primary_region_name }}"
  no_log: True

- name: Configure Docker Registry.
  block:
    - name: Create Docker Registry config directory.
      file:
        path: "{{ docker_registry_config_path }}"
        state: directory
    - name: Create Docker Registry config.
      template:
        src: config.yml.j2
        dest: "{{ docker_registry_config_path }}/config.yml"
      notify:
        - restart docker registry
    - name: Configure Docker Registry systemd service.
      template:
        src: docker_registry.service.j2
        dest: "/etc/systemd/system/{{ docker_registry_service_name }}.service"
      notify:
        - restart docker registry
  tags:
    - configuration

- name: Enable Docker Registry service on boot.
  systemd:
    service: "{{ docker_registry_service_name }}"
    # TODO: this is a thorny part of ansible and we shouldn't have to do this ourselves.
    daemon_reload: yes
    state: started
    enabled: yes
