---
name: CI for chi-in-a-box script

on:
  push:
  pull_request:

jobs:
  test:
    name: test cc-ansible
    runs-on: 	[self-hosted, kvm, ciab, ubuntu-18.04]
    env:
      CC_ANSIBLE_SITE: /opt/site-config
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2
      - name: init site-config
        run: "./cc-ansible init"
        continue-on-error: true
      - run: "./cc-ansible bootstrap-servers"
      - run: "./cc-ansible prechecks"
      - run: "./cc-ansible pull"
      - run: "./cc-ansible genconfig"
