---
name: CI for chi-in-a-box script

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        include:
          # - { runner: [self-hosted, kvm, ciab, ubuntu-18.04] }
          - { runner: ubuntu-18.04 } # use github hosted runner
    name: test cc-ansible
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install virtualenv and jq
        run: |
          sudo apt-get update && sudo apt-get install -f -y \
          jq \
          virtualenv
      - name: set site-config path
        run: echo "CC_ANSIBLE_SITE=${{ runner.temp }}/site-config" >> $GITHUB_ENV
      - name: init site-config
        run: "./cc-ansible init"
      - run: "./cc-ansible bootstrap-servers"
      - run: "./cc-ansible prechecks"
      - run: "./cc-ansible pull"
      - run: "./cc-ansible genconfig"
