---
name: CI for chi-in-a-box script

on:
  push:
    branches:
      - main
      - stable/*
  pull_request:
    branches:
      - main
      - stable/*
  workflow_dispatch: {}

jobs:
  ci:
    name: basic setup checks
    runs-on: 	[ ubuntu-22.04 ]
    env:
      CC_ANSIBLE_SITE: /opt/site-config
    steps:

      - name: checkout chi-in-a-box
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: setup dummy network interfaces
        run: tests/setup_ifaces.sh

      - name: install deps
        run: ./cc-ansible install_deps

      - name: initialize site-config
        run: ./cc-ansible init

      # TODO: Parameterize config file choice
      - name: configure site for test config
        run: cp tests/configs/chi_edge.yaml ${CC_ANSIBLE_SITE}/defaults.yaml

      - name: bootstrap system
        run: ./cc-ansible bootstrap-servers

      - name: pull containers
        run: ./cc-ansible pull

      - name: generate configs
        run: ./cc-ansible genconfig

      - name: deploy services
        run: ./cc-ansible deploy
