---
name: CI for chi-in-a-box script

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        include:
          # - { runner: [self-hosted, kvm, ciab, ubuntu-18.04] }
          - { runner: ubuntu-18.04 } # use github hosted runner
    name: test cc-ansible
    runs-on: ${{ matrix.runner }}
    env:
      CC_ANSIBLE_SITE: /opt/site-config
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2
      - name: init site-config
        run: "./cc-ansible init"
      - run: "./cc-ansible bootstrap-servers"
      - run: "./cc-ansible prechecks"
      - run: "./cc-ansible pull"
      - run: "./cc-ansible genconfig"
