---

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      CC_ANSIBLE_SITE: /opt/site-config
    steps:
      - name: checkout chi-in-a-box
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: ./cc-ansible install_deps -v
      - run: ./cc-ansible init -v
      - run: ./cc-ansible bootstrap_servers -v
      - run: ./cc-ansible deploy -v
      - run: ./cc-ansible post-deploy -v
