name: Docs Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    name: build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: install docs deps
        run: pip install -r docs/requirements.txt
      - name: build docs
        run: mkdocs build
